import React, { useEffect, useState } from "react";
import { motion } from "motion/react";
import {
  Users, ArrowLeft, MoreHorizontal,
  LogOut, TrendingUp, RefreshCw, FileText,
  Search, Globe, Star, UserCheck, Calendar, X, Filter,
  Presentation, Play, ChevronRight, Check, XCircle,
  MessageSquare, Send, Instagram, MessageCircle, CreditCard, Sparkles, ChevronDown, MapPin, Link2, AlertTriangle
} from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { supabase, type ConsultationRequest } from "../lib/supabase";
import { generateDailyBriefing } from "../lib/ai-assistant-service";
import { AnimatePresence } from "motion/react";
import { DndContext, closestCenter, KeyboardSensor, PointerSensor, useSensor, useSensors, DragEndEvent, useDroppable } from '@dnd-kit/core';
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';

// Assets for PT Mode (Generated by AntiGravity)
const PT_ASSETS: Record<string, { image: string; title: string; benefit: string; script: string }> = {
  "Dental Implants": {
    image: "/brain/0774c8b3-dc9c-4ab9-82fe-cc27c1e404a8/dental_implant_3d_visual_1772134009341.png",
    title: "Precision Implantology",
    benefit: "Implants look and function like natural teeth, preserving your jawbone and facial structure.",
    script: "As you can see from our 3D analysis, we precisely map your nerves and bone structure for a perfect placement. This investment restores your smile for a lifetime."
  },
  "Veneers": {
    image: "/brain/0774c8b3-dc9c-4ab9-82fe-cc27c1e404a8/veneer_before_after_mockup_1772134023178.png",
    title: "Hollywood Smile Makeover",
    benefit: "Ultra-thin porcelain veneers correct shape, color, and alignment in as little as two visits.",
    script: "Look at the transformation. Veneers are an art form that creates total facial harmony. It's the gold standard for achieving a celebrity-level smile with minimal invasion."
  },
  "Invisalign / Aligners": {
    image: "/brain/0774c8b3-dc9c-4ab9-82fe-cc27c1e404a8/invisalign_simulation_ui_1772134037487.png",
    title: "SmartSmile Aligner Simulation",
    benefit: "Straighten your teeth invisibly with removable aligners and see your final result before you start.",
    script: "Notice how your teeth will shift over the next 6 months. We can project your exact final result today. It's the most discreet and comfortable way to achieve perfection."
  }
};

// Removed PresentationOverlay as PT Mode is now strictly patient-facing at /pt/:id

function timeAgo(dateStr: string): string {
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "Just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  if (days < 7) return `${days}d ago`;
  return new Date(dateStr).toLocaleDateString("en-GB", { day: "numeric", month: "short" });
}

const TREATMENT_VALUES: Record<string, number> = {
  "Dental Implants": 3000,
  "Invisalign / Aligners": 2500,
  "Veneers": 1200,
  "Composite Bonding": 800,
  "Teeth Whitening": 500,
  "Dental Crown": 900,
  "Emergency Appointment": 300,
  "General Inquiry": 1500,
  "Other": 1000,
};

const STATUS_COLORS: Record<string, string> = {
  "New": "text-blue-400 border-blue-400/40 bg-blue-400/10",
  "Contacted": "text-yellow-400 border-yellow-400/40 bg-yellow-400/10",
  "Consultation Booked": "text-purple-400 border-purple-400/40 bg-purple-400/10",
  "Visited": "text-green-400 border-green-400/40 bg-green-400/10",
  "Treatment Started": "text-white border-white/40 bg-white/10",
  "Abandoned": "text-white/30 border-white/10 bg-white/5",
};

const STAFF_LIST = ["Alice", "Bob", "Charlotte", "David", "Emma"];

// ── Animated SVG Donut Chart ─────────────────────────────────────────────
interface DonutSegment {
  label: string;
  count: number;
  color: string;
  hex: string;
}

function DonutChart({ segments, total, totalValue }: { segments: DonutSegment[]; total: number; totalValue: number }) {
  const [animated, setAnimated] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => setAnimated(true), 200);
    return () => clearTimeout(timer);
  }, []);

  const size = 180;
  const strokeWidth = 28;
  const radius = (size - strokeWidth) / 2;
  const circumference = 2 * Math.PI * radius;
  const cx = size / 2;
  const cy = size / 2;

  // Build dash segments
  let cumulativePercent = 0;
  const segmentElements = segments.map((seg, i) => {
    const percent = total > 0 ? seg.count / total : 0;
    const dashArray = circumference * percent;
    const dashOffset = circumference * (1 - cumulativePercent);
    cumulativePercent += percent;

    return (
      <circle
        key={seg.label}
        cx={cx}
        cy={cy}
        r={radius}
        fill="none"
        stroke={seg.hex}
        strokeWidth={strokeWidth}
        strokeDasharray={`${animated ? dashArray : 0} ${circumference}`}
        strokeDashoffset={dashOffset}
        strokeLinecap="butt"
        transform={`rotate(-90 ${cx} ${cy})`}
        style={{ transition: `stroke-dasharray 0.8s ease ${i * 0.15}s` }}
      />
    );
  });

  return (
    <div className="flex flex-col items-center">
      <div className="relative">
        <svg width={size} height={size}>
          {/* Background ring */}
          <circle
            cx={cx} cy={cy} r={radius}
            fill="none"
            stroke="rgba(255,255,255,0.05)"
            strokeWidth={strokeWidth}
          />
          {segmentElements}
        </svg>
        {/* Centre label */}
        <div className="absolute inset-0 flex flex-col items-center justify-center gap-1 mt-1">
          <div className="flex flex-col items-center">
            <span className="text-xl font-bold text-white leading-none">{total}</span>
            <span className="text-[9px] text-white/40 uppercase tracking-widest font-bold">Leads</span>
          </div>
          <div className="w-8 h-px bg-white/20 my-0.5" />
          <div className="flex flex-col items-center">
            <span className="text-[15px] font-bold text-blue-400 leading-none">£{(totalValue / 1000).toFixed(1)}k</span>
            <span className="text-[9px] text-white/40 uppercase tracking-widest font-bold">Value</span>
          </div>
        </div>
      </div>

      {/* Legend */}
      <div className="mt-6 w-full space-y-3">
        {segments.map((seg) => {
          const pct = total > 0 ? Math.round((seg.count / total) * 100) : 0;
          return (
            <div key={seg.label} className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="w-2.5 h-2.5 rounded-full flex-shrink-0" style={{ background: seg.hex }} />
                <span className="text-[11px] text-white/50 font-medium">{seg.label}</span>
              </div>
              <span className="text-[11px] font-bold text-white/80">
                {seg.count} <span className="text-white/30">({pct}%)</span>
              </span>
            </div>
          );
        })}
      </div>
    </div>
  );
}
// ── Kanban Drag & Drop Wrapper ───────────────────────────────────────────

function SortableLeadCard({
  id,
  lead,
  setDepositModal,
  setSelectedLead,
  updateStatus,
  STAFF_LIST,
  updateAssignedTo,
  timeAgo
}: {
  id: string;
  lead: ConsultationRequest;
  setDepositModal: any;
  setSelectedLead: any;
  updateStatus: any;
  STAFF_LIST: string[];
  updateAssignedTo: any;
  timeAgo: any;
}) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging
  } = useSortable({ id });

  const [isSendingEmail, setIsSendingEmail] = useState(false);

  const handleSendEmail = async (e: React.MouseEvent) => {
    e.stopPropagation();
    setIsSendingEmail(true);
    try {
      const response = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/send-pt-link`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}`
        },
        body: JSON.stringify({
          lead_id: lead.id,
          name: lead.name,
          email: lead.email,
          service: lead.service
        })
      });

      if (!response.ok) throw new Error("Failed to send email");
      alert(`PT Link successfully sent to ${lead.email}!`);
    } catch (err) {
      console.error(err);
      alert("Error sending email. Please try again.");
    } finally {
      setIsSendingEmail(false);
    }
  };

  const style = {
    transform: CSS.Transform.toString(transform),
    transition: isDragging ? transition : "transform 400ms cubic-bezier(0.18, 0.67, 0.6, 1.22)", // Spring effect on drop
    zIndex: isDragging ? 50 : 1,
  };

  return (
    <div ref={setNodeRef} style={style} className="mb-3 outline-none">
      <motion.div
        animate={{
          scale: isDragging ? 1.06 : 1,
          rotate: isDragging ? 1.5 : 0,
          boxShadow: isDragging
            ? "0 40px 80px rgba(0,0,0,0.5), 0 0 0 1px rgba(255,255,255,0.15)"
            : "0 0 0 1px rgba(255,255,255,0)",
          opacity: isDragging ? 0.95 : 1,
          y: isDragging ? -10 : 0
        }}
        transition={{ type: "spring", stiffness: 500, damping: 30, mass: 0.8 }}
        className={`bg-[#0d0d0d] border rounded-2xl p-5 relative group focus:outline-none transition-colors ${isDragging ? 'border-white/30 cursor-grabbing' : 'border-white/[0.05] hover:border-white/20 cursor-grab'
          }`}
      >
        {/* Drag Handle Area */}
        <div {...attributes} {...listeners} className="absolute inset-0 z-0 outline-none rounded-2xl" />

        {/* Content Area */}
        <div className="relative z-10 pointer-events-none">
          <div className="flex justify-between items-start mb-2">
            <h4 className="font-bold text-sm text-white uppercase tracking-tight truncate mr-2">{lead.name}</h4>
            <span className="text-[9px] font-bold text-white/20 uppercase tracking-widest shrink-0">{timeAgo(lead.created_at)}</span>
          </div>

          <div className="flex flex-wrap gap-2 mb-4">
            <span className="px-2 py-0.5 rounded-full text-[9px] font-bold tracking-widest uppercase border bg-green-400/10 text-green-400 border-green-400/30">
              £{TREATMENT_VALUES[lead.service]?.toLocaleString() ?? "1,000"}
            </span>
            <span className={`px-2 py-0.5 rounded-full text-[9px] font-bold tracking-widest uppercase border ${lead.service.includes("Implant") || lead.service.includes("Invisalign") || lead.service.includes("Veneer")
              ? "bg-cyan-400/10 text-cyan-400 border-cyan-400/30"
              : "bg-white/5 text-white/40 border-white/10"
              }`}>
              {lead.service}
            </span>
            {lead.name.toLowerCase().includes("vip") && (
              <span className="bg-pink-500/10 text-pink-500 border border-pink-500/30 px-2 py-0.5 rounded-full text-[9px] font-bold tracking-widest uppercase">VIP</span>
            )}
          </div>

          <div className="flex items-center gap-3 mt-3 text-[10px] text-white/50 font-bold uppercase tracking-widest border-t border-white-[0.05] pt-3">
            {lead.phone && <span className="text-[#22d3ee] flex items-center gap-1.5"><svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" /></svg>{lead.phone}</span>}
          </div>
        </div>

        {/* Compact Quick Actions */}
        <div className="relative z-20 flex gap-2 mt-5 opacity-0 group-hover:opacity-100 transition-all duration-300 transform translate-y-2 group-hover:translate-y-0">
          {lead.status !== "Treatment Started" && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                if (window.confirm(`Mark ${lead.name}'s treatment as Paid & Started?`)) {
                  updateStatus(lead.id, "Treatment Started");
                }
              }}
              className="px-3 flex items-center gap-2 justify-center text-[#00ffcc] hover:text-[#00ffcc] bg-[#00ffcc]/10 hover:bg-[#00ffcc]/30 rounded-xl transition-all border border-[#00ffcc]/20 font-bold uppercase tracking-widest text-[9px]"
              title="Mark as Paid (Moves to Treatment Started)"
            >
              <Check className="w-3.5 h-3.5" /> MARK PAID
            </button>
          )}
          <button
            onClick={handleSendEmail}
            disabled={isSendingEmail}
            className="px-3 flex items-center justify-center text-green-400 hover:text-white bg-green-400/10 hover:bg-green-400/30 rounded-xl transition-all border border-green-400/20 disabled:opacity-50"
            title="Send PT Link via Email"
          >
            {isSendingEmail ? <RefreshCw className="w-3.5 h-3.5 animate-spin text-green-400" /> : <Send className="w-3.5 h-3.5" />}
          </button>
          <button
            onClick={(e) => {
              e.stopPropagation();
              const url = `${window.location.origin}/pt/${lead.id}`;
              navigator.clipboard.writeText(url);
              alert("Patient PT Link copied to clipboard!");
            }}
            className="px-3 flex items-center justify-center text-cyan-400 hover:text-white bg-cyan-400/5 hover:bg-cyan-400/20 rounded-xl transition-all border border-cyan-400/10"
            title="Copy Shareable PT Link"
          >
            <Link2 className="w-3.5 h-3.5" />
          </button>
          <button
            onClick={(e) => {
              e.stopPropagation();
              setSelectedLead(lead);
            }}
            className="px-3 flex items-center justify-center text-white/40 hover:text-white bg-white/5 hover:bg-white/10 rounded-xl transition-all border border-white/10"
            title={lead.status === "New" || lead.status === "Contacted" || lead.status === "Consultation Booked" ? "View Inquiry Details" : "View Patient Chart"}
          >
            <FileText className="w-3.5 h-3.5" />
          </button>
        </div>
      </motion.div>
    </div>
  );
}

function KanbanColumn({
  columnId,
  columnLeads,
  setDepositModal,
  setSelectedLead,
  updateStatus,
  STAFF_LIST,
  updateAssignedTo,
  timeAgo
}: {
  columnId: string;
  columnLeads: ConsultationRequest[];
  setDepositModal: any;
  setSelectedLead: any;
  updateStatus: any;
  STAFF_LIST: string[];
  updateAssignedTo: any;
  timeAgo: any;
}) {
  const { setNodeRef } = useDroppable({ id: columnId });

  return (
    <div className="w-[280px] shrink-0 flex flex-col h-[calc(100vh-280px)] border-r border-white-[0.03] pr-4 mr-4 last:border-r-0 last:mr-0 last:pr-0">
      <div className="flex justify-between items-center mb-5 px-1">
        <h3 className="text-[13px] font-semibold text-white/70 flex items-center gap-2">
          {columnId === "Consultation Booked" ? "Booked" : columnId}
          <span className="text-[10px] font-medium text-white/40 bg-white/5 border border-white/10 px-1.5 py-0.5 rounded-md">{columnLeads.length}</span>
        </h3>
        {columnLeads.length > 0 && (
          <span className="text-[10px] font-bold text-green-400/80 tracking-wider">
            £{columnLeads.reduce((sum, l) => sum + (TREATMENT_VALUES[l.service] ?? 1000), 0).toLocaleString()}
          </span>
        )}
      </div>

      {/* Droppable Column Area */}
      <div className="flex-1 overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none] outline-none" ref={setNodeRef}>
        <SortableContext items={columnLeads.map(l => l.id)}>
          {columnLeads.map(lead => (
            <SortableLeadCard
              key={lead.id}
              id={lead.id}
              lead={lead}
              setDepositModal={setDepositModal}
              setSelectedLead={setSelectedLead}
              updateStatus={updateStatus}
              STAFF_LIST={STAFF_LIST}
              updateAssignedTo={updateAssignedTo}
              timeAgo={timeAgo}
            />
          ))}
        </SortableContext>
        {columnLeads.length === 0 && (
          <div className="h-24 rounded-xl flex flex-col items-center justify-center opacity-30 mt-2 border border-dashed border-white/10 bg-white/[0.01]">
            <span className="text-[11px] font-semibold text-white/40">Drop here</span>
          </div>
        )}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────

const KANBAN_COLUMNS = ["New", "Contacted", "Consultation Booked", "Visited", "Treatment Started"];
const BRANCHES = ["London HQ", "Manchester Clinic", "Birmingham Center", "Edinburgh Practice"];

export default function AdminDashboard() {
  const navigate = useNavigate();
  const [session, setSession] = useState<boolean | null>(null);
  const [multiBranchMode, setMultiBranchMode] = useState(false);
  const [selectedBranch, setSelectedBranch] = useState(BRANCHES[0]);
  const [isBranchDropdownOpen, setIsBranchDropdownOpen] = useState(false);
  const [leads, setLeads] = useState<ConsultationRequest[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedLead, setSelectedLead] = useState<ConsultationRequest | null>(null);
  const [isRecording, setIsRecording] = useState(false);
  const [dictationText, setDictationText] = useState("");
  const [activeTab, setActiveTab] = useState<"leads" | "analytics" | "staff" | "inbox">("leads");
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedDate, setSelectedDate] = useState<string>("");
  const [selectedChat, setSelectedChat] = useState<number | null>(0);
  const [replyText, setReplyText] = useState("");
  const [depositModal, setDepositModal] = useState<{ isOpen: boolean; leadName: string; payUrl: string }>({ isOpen: false, leadName: "", payUrl: "" });
  const [aiBriefing, setAiBriefing] = useState<string | null>(null);
  const [draftDropoffs, setDraftDropoffs] = useState(0);

  useEffect(() => {
    const fetchDrafts = async () => {
      const fifteenMinsAgo = new Date(Date.now() - 15 * 60000).toISOString();
      const { count } = await supabase
        .from('appointments')
        .select('*', { count: 'exact', head: true })
        .eq('status', 'draft')
        .lt('created_at', fifteenMinsAgo);
      if (count !== null) setDraftDropoffs(count);
    };
    if (session) {
      fetchDrafts();
      const interval = setInterval(fetchDrafts, 60000); // Check every minute
      return () => clearInterval(interval);
    }
  }, [session]);

  useEffect(() => {
    if (leads.length > 0 && !aiBriefing) {
      generateDailyBriefing(leads).then(setAiBriefing);
    }
  }, [leads, aiBriefing]);

  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 5 } }),
    useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates })
  );

  const mockChats = [
    {
      id: 0, recipient: "Lee Min-ho", source: "Instagram", avatar: "LM", lastMsg: "Veneer treatment costs?", time: "2m ago", unread: true, messages: [
        { sender: "patient", text: "Hi, how much for veneers?", time: "2:00 PM" },
        { sender: "staff", text: "Hello! Our veneers start from £800 per tooth. Would you like a consultation?", time: "2:05 PM" },
        { sender: "patient", text: "Do you offer any payment plans?", time: "2:10 PM" }
      ]
    },
    {
      id: 1, recipient: "Kim Ji-soo", source: "Kakao", avatar: "KJ", lastMsg: "Booking next week.", time: "15m ago", unread: false, messages: [
        { sender: "patient", text: "Can I book for Monday 2PM?", time: "1:45 PM" }
      ]
    },
    {
      id: 2, recipient: "Park Seo-jun", source: "Website", avatar: "PS", lastMsg: "Thanks for the guide!", time: "1h ago", unread: false, messages: [
        { sender: "staff", text: "You're welcome! Let us know if you have questions.", time: "12:30 PM" },
        { sender: "patient", text: "The prep guide was very helpful, thanks!", time: "1:00 PM" }
      ]
    }
  ];

  useEffect(() => {
    supabase.auth.getSession().then(({ data }) => {
      setSession(!!data.session);
    });
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_e, s) => {
      setSession(!!s);
      if (s) fetchLeads();
    });
    return () => subscription.unsubscribe();
  }, []);

  useEffect(() => {
    if (session) fetchLeads();
  }, [session]);

  const fetchLeads = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from("consultation_requests")
      .select("*")
      .order("created_at", { ascending: false });

    if (!error && data) setLeads(data as ConsultationRequest[]);
    setLoading(false);
  };

  const updateStatus = async (id: string, newStatus: ConsultationRequest["status"]) => {
    // Validation
    if (!KANBAN_COLUMNS.includes(newStatus)) {
      console.error("Attempted to update to invalid status:", newStatus);
      return;
    }

    const lead = leads.find(l => l.id === id);
    const updateData: any = {
      status: newStatus
    };

    // Auto-schedule recall for completed/archived leads
    if (newStatus === 'Visited' || newStatus === 'Archived' || newStatus === 'Abandoned') {
      updateData.recall_interval_months = 6;
    }

    // Track first contact time
    if (lead?.status === "New" && newStatus !== "New" && !lead?.first_contact_at) {
      updateData.first_contact_at = new Date().toISOString();
    }

    const { error } = await supabase
      .from("consultation_requests")
      .update(updateData)
      .eq("id", id);

    if (error) {
      console.error("Error updating status:", error);
      alert(`Update failed: ${error.message}. The board will refresh.`);
      fetchLeads(); // Rollback optimistic update
      return;
    }

    // Auto-trigger review email when status → "Visited"
    if (newStatus === "Visited" && lead && !lead.review_requested_at && lead.email) {
      const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
      const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
      fetch(`${supabaseUrl}/functions/v1/review-request`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "apikey": anonKey,
          "Authorization": `Bearer ${anonKey}`,
        },
        body: JSON.stringify({ lead_id: id, name: lead.name, email: lead.email, service: lead.service }),
      }).catch(e => console.error("Review request error:", e));
    }

    fetchLeads();
  };

  const handleDragEnd = async (event: DragEndEvent) => {
    const { active, over } = event;
    if (!over) return;

    const leadId = active.id as string;
    let newStatus = over.id as string;

    // If dropped over another lead card, find that lead's status
    if (!KANBAN_COLUMNS.includes(newStatus)) {
      const overLead = leads.find(l => l.id === newStatus);
      if (overLead) {
        newStatus = overLead.status;
      } else {
        // Validation: If it's still not a column name, it's invalid
        console.warn("Invalid drop target:", newStatus);
        return;
      }
    }

    // Safety: Ensure newStatus is a valid column name and NOT a UUID
    if (!KANBAN_COLUMNS.includes(newStatus)) {
      console.error("Critical: newStatus is not a valid column:", newStatus);
      return;
    }

    const lead = leads.find(l => l.id === leadId);
    if (lead && lead.status !== newStatus) {
      // Optimistic UI Update
      setLeads(prev => prev.map(l => l.id === leadId ? { ...l, status: newStatus as ConsultationRequest["status"] } : l));
      await updateStatus(leadId, newStatus as ConsultationRequest["status"]);
    }
  };

  const handleMicClick = () => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      alert("Voice dictation is not supported in this browser. Please use Chrome.");
      return;
    }

    const recognition = new SpeechRecognition();
    recognition.lang = 'en-US';
    recognition.interimResults = false;
    recognition.maxAlternatives = 1;

    recognition.onstart = () => {
      setIsRecording(true);
    };

    recognition.onresult = (event: any) => {
      const transcript = event.results[0][0].transcript;
      setDictationText(prev => prev ? prev + " " + transcript : transcript);
    };

    recognition.onerror = (event: any) => {
      console.error("Speech recognition error", event.error);
      setIsRecording(false);
    };

    recognition.onend = () => {
      setIsRecording(false);
    };

    recognition.start();
  };

  const saveNotes = async () => {
    if (!selectedLead) return;
    const newNotes = dictationText;

    // Optimistic UI Update
    setLeads(prev => prev.map(l => l.id === selectedLead.id ? { ...l, notes: newNotes } : l));
    setSelectedLead({ ...selectedLead, notes: newNotes });
    setDictationText("");

    const { error } = await supabase.from("consultation_requests").update({ notes: newNotes }).eq('id', selectedLead.id);
    if (error) {
      alert("Error saving notes: " + error.message);
      fetchLeads(); // Rollback
    }
  };

  // Sync dictationText when selectedLead changes
  useEffect(() => {
    if (selectedLead) {
      setDictationText(selectedLead.notes || "");
    }
  }, [selectedLead]);

  const updateAssignedTo = async (id: string, staffName: string) => {
    await supabase
      .from("consultation_requests")
      .update({ assigned_to: staffName || null })
      .eq("id", id);
    fetchLeads();
  };

  const handleLogout = async () => {
    await supabase.auth.signOut();
    setSession(false);
    setLeads([]);
  };

  useEffect(() => {
    if (session === false) {
      navigate("/login");
    }
  }, [session, navigate]);

  if (session === null || session === false) {
    return (
      <div className="min-h-screen bg-[#050505] flex items-center justify-center">
        <RefreshCw className="w-6 h-6 text-white/20 animate-spin" />
      </div>
    );
  }

  // ── Stats ──
  const now = new Date();
  const currentMonth = now.getMonth();
  const currentYear = now.getFullYear();

  const thisMonthLeads = leads.filter(l => {
    const d = new Date(l.created_at);
    return d.getMonth() === currentMonth && d.getFullYear() === currentYear;
  });

  const totalLeads = leads.length;
  const thisMonthNew = thisMonthLeads.length;

  const newLeads = leads.filter(l => l.status === "New").length;
  const newLeadsValue = leads.filter(l => l.status === "New").reduce((sum, l) => sum + (TREATMENT_VALUES[l.service] ?? 1000), 0);
  const ghostPatients = leads.filter(l => l.status === "Abandoned").length;
  const ghostLoss = leads.filter(l => l.status === "Abandoned").reduce((sum, l) => sum + (TREATMENT_VALUES[l.service] ?? 1000), 0);
  const confirmedLeads = totalLeads - ghostPatients;

  const allTimeRevenue = leads.filter(l => l.status === "Treatment Started").reduce((sum, l) => sum + (TREATMENT_VALUES[l.service] ?? 1000), 0);
  const monthlySecuredRevenue = thisMonthLeads.filter(l => l.status === "Treatment Started").reduce((sum, l) => sum + (TREATMENT_VALUES[l.service] ?? 1000), 0);

  const monthlyPipelineRemaining = thisMonthLeads.reduce((sum, l) => {
    if (l.status === "Abandoned" || l.status === "Treatment Started") return sum;
    return sum + (TREATMENT_VALUES[l.service] ?? 1000);
  }, 0);

  const pipelineValue = leads.reduce((sum, l) => {
    if (l.status === "Abandoned" || l.status === "Treatment Started") return sum;
    return sum + (TREATMENT_VALUES[l.service] ?? 1000);
  }, 0);

  // ── Source segments for donut ──
  const directCount = leads.filter(l => !l.utm_source && !l.referrer).length;
  const googleCount = leads.filter(l => l.utm_source === "google" || l.utm_source?.includes("search")).length;
  const socialCount = leads.filter(l => l.referrer || (l.utm_source && l.utm_source !== "google")).length;

  const sourceSegments: DonutSegment[] = [
    { label: "Direct Traffic", count: directCount, color: "bg-white/40", hex: "rgba(255,255,255,0.5)" },
    { label: "Google / Search", count: googleCount, color: "bg-blue-400", hex: "#60a5fa" },
    { label: "Referrer / Social", count: socialCount, color: "bg-purple-400", hex: "#c084fc" },
  ];

  // Dynamic insight: find top source
  const topSource = [...sourceSegments].sort((a, b) => b.count - a.count)[0];

  // ── Recharts HQ Data Simulation ──
  const revenueData = [
    { name: 'Week 1', Implement: 12000, Invisalign: 8000, Veneers: 5000 },
    { name: 'Week 2', Implement: 15000, Invisalign: 9000, Veneers: 6000 },
    { name: 'Week 3', Implement: 18000, Invisalign: 11000, Veneers: 7000 },
    { name: 'Week 4', Implement: 22000, Invisalign: 14000, Veneers: 9000 },
  ];
  const topSourceTip: Record<string, string> = {
    "Direct Traffic": "Most of your leads come directly — your brand awareness is strong. Consider adding referral incentives to grow this further.",
    "Google / Search": "Google leads are converting well. Consider increasing your budget for high-value treatment keywords like \"Dental Implants London\".",
    "Referrer / Social": "Social/referral traffic is your top source. Double down on Instagram and patient testimonial content.",
  };

  return (
    <div className="min-h-screen bg-[#050505] text-white p-6 md:p-10">

      {/* Drop-off Defense Banner */}
      {draftDropoffs > 0 && (
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-6 mx-auto max-w-7xl bg-[#00ffcc]/10 border border-[#00ffcc]/20 rounded-2xl p-5 flex items-center justify-between shadow-[0_0_30px_rgba(0,255,204,0.15)]"
        >
          <div className="flex items-center gap-4">
            <span className="flex h-4 w-4 relative">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-[#00ffcc]/60 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-4 w-4 bg-[#00ffcc] shadow-[0_0_10px_#00ffcc]"></span>
            </span>
            <p className="text-[#00ffcc] text-sm font-medium">
              <span className="font-bold uppercase tracking-widest text-xs mr-3 text-[#00ffcc] bg-[#00ffcc]/20 px-2 py-1 rounded-md">VIP Drop-off Alert</span>
              15분 이상 <code className="bg-[#00ffcc]/10 px-1 py-0.5 rounded text-[#00ffcc]/80">draft</code> 상태인 대기 예약 {draftDropoffs}건 발견 (하이엔드 리타겟팅 발동 대기중)
            </p>
          </div>
          <button
            onClick={() => {
              // Trigger edge function or open action tab manually
              alert(`Retargeting webhook fired for ${draftDropoffs} abandoned drafts. SMS & Email sequence initiated!`);
            }}
            className="px-5 py-2.5 bg-[#00ffcc]/20 hover:bg-[#00ffcc]/30 text-[#00ffcc] font-bold uppercase tracking-widest text-xs rounded-xl transition-all border border-[#00ffcc]/30 hover:shadow-[0_0_15px_rgba(0,255,204,0.3)] hover:scale-105 active:scale-95 duration-200">
            즉시 구출 (Save Leads)
          </button>
        </motion.div>
      )}

      {/* Invalid Status Repair Banner */}
      {leads.some(l => !KANBAN_COLUMNS.includes(l.status)) && (
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="mb-6 mx-auto max-w-7xl bg-red-500/10 border border-red-500/20 rounded-2xl p-5 flex items-center justify-between shadow-[0_0_30px_rgba(239,68,68,0.15)]"
        >
          <div className="flex items-center gap-4">
            <AlertTriangle className="w-5 h-5 text-red-500" />
            <p className="text-red-500 text-sm font-medium">
              <span className="font-bold uppercase tracking-widest text-xs mr-3 text-red-500 bg-red-500/20 px-2 py-1 rounded-md">Database Corruption</span>
              {leads.filter(l => !KANBAN_COLUMNS.includes(l.status)).length} leads have invalid status data and are hidden.
            </p>
          </div>
          <button
            onClick={async () => {
              const invalidLeads = leads.filter(l => !KANBAN_COLUMNS.includes(l.status));
              for (const l of invalidLeads) {
                await supabase.from("consultation_requests").update({ status: 'New' }).eq('id', l.id);
              }
              fetchLeads();
              alert("Database repair complete! All corrupted leads reset to 'New'.");
            }}
            className="px-5 py-2.5 bg-red-500 text-white font-bold uppercase tracking-widest text-xs rounded-xl transition-all border border-red-400/30 hover:shadow-[0_0_15px_rgba(239,68,68,0.3)] hover:scale-105 active:scale-95 duration-200">
            Fix Database Now
          </button>
        </motion.div>
      )}

      {/* Action Required Banner for New Leads */}
      {newLeads > 0 && (
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8 mx-auto max-w-7xl bg-[#00ffcc]/10 border border-[#00ffcc]/20 rounded-2xl p-5 flex flex-col md:flex-row items-start md:items-center justify-between shadow-[0_0_30px_rgba(0,255,204,0.15)] gap-4"
        >
          <div className="flex items-center gap-4">
            <span className="flex h-4 w-4 relative shrink-0">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-[#00ffcc]/60 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-4 w-4 bg-[#00ffcc] shadow-[0_0_10px_#00ffcc]"></span>
            </span>
            <p className="text-[#00ffcc] text-sm font-medium">
              <span className="font-bold uppercase tracking-widest text-xs mr-3 text-[#00ffcc] bg-[#00ffcc]/20 px-2 py-1 rounded-md">🚨 ACTION REQUIRED</span>
              High-value lead is waiting. Call now to secure <strong className="text-white">£{newLeadsValue.toLocaleString()}</strong> revenue.
            </p>
          </div>
        </motion.div>
      )}

      <AnimatePresence>
        {selectedLead && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[3000] bg-black/80 backdrop-blur-md flex flex-col items-center justify-center p-6"
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0, y: 30 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.95, opacity: 0, y: -20 }}
              className="bg-[#0f0f0f] border border-white/10 p-8 rounded-[32px] max-w-2xl w-full text-left relative overflow-hidden flex flex-col shadow-2xl"
            >
              <button
                onClick={() => setSelectedLead(null)}
                className="absolute top-6 right-6 p-2 bg-white/5 hover:bg-white/10 rounded-full transition-colors"
              >
                <X className="w-5 h-5 text-white/40" />
              </button>

              <div className="flex items-center gap-4 mb-8">
                <div className="w-16 h-16 bg-white/5 rounded-2xl flex items-center justify-center border border-white/10">
                  <UserCheck className="w-8 h-8 text-white/50" />
                </div>
                <div>
                  <h2 className="text-3xl font-display font-bold text-white uppercase tracking-tight">{selectedLead.name}</h2>
                  <div className="flex items-center gap-3 mt-1.5 text-xs font-bold text-white/40 uppercase tracking-widest">
                    <span>{selectedLead.service}</span>
                    <span className="w-1 h-1 bg-white/20 rounded-full" />
                    <span>{selectedLead.phone}</span>
                  </div>
                </div>
              </div>

              <div className="bg-white/[0.02] border border-white/5 rounded-2xl p-6 mb-6">
                <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/30 mb-4 flex items-center gap-2">
                  <FileText className="w-3.5 h-3.5" /> {selectedLead.status === "Visited" || selectedLead.status === "Treatment Started" ? "Clinical Notes & Chart" : "Initial Inquiry & Notes"}
                </h3>
                <div className="text-sm text-white/90 leading-relaxed font-medium min-h-[100px] max-h-[250px] overflow-y-auto whitespace-pre-wrap bg-white/5 p-4 rounded-xl border border-white/5">
                  {selectedLead.notes || <span className="text-white/40 italic">No detailed inquiry notes provided.</span>}
                </div>
              </div>

              <div className="relative mb-6">
                <textarea
                  value={dictationText}
                  onChange={(e) => setDictationText(e.target.value)}
                  placeholder="Type notes or click the microphone to dictate..."
                  className="w-full h-32 bg-white/5 border border-white/10 rounded-2xl p-5 text-sm text-white placeholder:text-white/20 focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all resize-none"
                />

                <button
                  onClick={handleMicClick}
                  className={`absolute bottom-4 right-4 p-4 rounded-xl shadow-lg transition-all ${isRecording
                    ? 'bg-red-500/20 text-red-500 hover:bg-red-500/30 border border-red-500/50 animate-pulse'
                    : 'bg-blue-500 text-white hover:bg-blue-600 border border-blue-400/50'
                    }`}
                >
                  <div className="flex items-center gap-2 font-bold uppercase tracking-widest text-[10px]">
                    {isRecording ? (
                      <>
                        <span className="w-2 h-2 rounded-full bg-red-500 animate-ping" />
                        Listening...
                      </>
                    ) : (
                      <>
                        <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" /><path d="M19 10v2a7 7 0 0 1-14 0v-2" /><line x1="12" x2="12" y1="19" y2="22" /></svg>
                        Dictate
                      </>
                    )}
                  </div>
                </button>
              </div>

              <div className="flex justify-end gap-3">
                <button
                  onClick={() => { setDictationText(""); setSelectedLead(null); }}
                  className="px-6 py-3 rounded-xl bg-white/5 text-white/50 hover:bg-white/10 hover:text-white text-xs font-bold uppercase tracking-widest transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={saveNotes}
                  disabled={!dictationText.trim()}
                  className="px-6 py-3 rounded-xl bg-white text-black hover:bg-gray-200 text-xs font-bold uppercase tracking-widest transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                >
                  <FileText className="w-4 h-4" /> {selectedLead.status === "Visited" || selectedLead.status === "Treatment Started" ? "Save to Chart" : "Save Notes"}
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}

        {depositModal.isOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[2000] bg-black/80 backdrop-blur-sm flex flex-col items-center justify-center p-6"
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="bg-[#0f0f0f] border border-white/10 p-8 rounded-3xl max-w-md w-full text-center relative overflow-hidden"
            >
              <button
                onClick={() => setDepositModal({ isOpen: false, leadName: "", payUrl: "" })}
                className="absolute top-4 right-4 p-2 bg-white/5 hover:bg-white/10 rounded-full transition-colors"
              >
                <X className="w-5 h-5 text-white/40" />
              </button>

              <div className="w-16 h-16 bg-[#E9F11E]/20 rounded-full flex items-center justify-center mx-auto mb-6">
                <Send className="w-8 h-8 text-[#E9F11E] ml-1" />
              </div>
              <h2 className="text-2xl font-display font-bold text-white mb-2 uppercase tracking-tight">Deposit Requested</h2>
              <p className="text-white/60 mb-6 text-sm">
                A secure payment link has been sent to <strong>{depositModal.leadName}</strong> via SMS and Email.
              </p>

              <div className="bg-white/5 border border-white/5 p-4 rounded-xl text-left mb-8">
                <span className="text-[10px] font-bold text-white/30 uppercase tracking-widest block mb-2">Generated Link (Copied to Clipboard)</span>
                <code className="text-[10px] text-blue-400 break-all select-all">{depositModal.payUrl}</code>
              </div>

              <button
                onClick={() => setDepositModal({ isOpen: false, leadName: "", payUrl: "" })}
                className="w-full py-4 bg-[#E9F11E] text-black font-bold uppercase tracking-widest text-sm rounded-xl hover:bg-yellow-400 transition-colors"
              >
                Done
              </button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="max-w-7xl mx-auto">

        {/* Header with Branch Selector */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
          <div>
            <Link to="/" className="text-white/30 hover:text-white flex items-center gap-2 mb-3 transition-colors text-xs font-bold uppercase tracking-widest">
              <ArrowLeft className="w-3.5 h-3.5" /> Back to Website
            </Link>
            <div className="flex items-center gap-4 relative">
              <h1 className="text-3xl font-display font-bold">HQ Dashboard</h1>

              {/* Branch Selector (Hidden by default based on User Feedback) */}
              {multiBranchMode && (
                <div className="relative">
                  <button
                    onClick={() => setIsBranchDropdownOpen(!isBranchDropdownOpen)}
                    className="flex items-center gap-2 bg-white/5 hover:bg-white/10 border border-white/10 px-4 py-2 rounded-xl text-sm font-bold transition-all text-white/80 group"
                  >
                    <MapPin className="w-4 h-4 text-white/40 group-hover:text-[#22d3ee]" />
                    {selectedBranch}
                    <ChevronDown className={`w-4 h-4 text-white/40 transition-transform ${isBranchDropdownOpen ? "rotate-180" : ""}`} />
                  </button>

                  <AnimatePresence>
                    {isBranchDropdownOpen && (
                      <motion.div
                        initial={{ opacity: 0, y: 10, scale: 0.95 }}
                        animate={{ opacity: 1, y: 0, scale: 1 }}
                        exit={{ opacity: 0, y: 10, scale: 0.95 }}
                        className="absolute top-full left-0 mt-2 w-56 bg-[#0f0f0f] border border-white/10 rounded-2xl p-2 z-[2000] shadow-2xl"
                      >
                        {BRANCHES.map(branch => (
                          <button
                            key={branch}
                            onClick={() => { setSelectedBranch(branch); setIsBranchDropdownOpen(false); }}
                            className={`w-full text-left px-4 py-2.5 rounded-xl text-sm font-medium transition-colors ${selectedBranch === branch
                              ? "bg-[#22d3ee]/10 text-[#22d3ee] font-bold"
                              : "text-white/60 hover:text-white hover:bg-white/5"
                              }`}
                          >
                            {branch}
                          </button>
                        ))}
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              )}
            </div>
            <p className="text-white/30 text-sm mt-2 font-medium">Enterprise Performance Overview</p>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={fetchLeads}
              className="p-2.5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition-colors"
            >
              <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} />
            </button>
            <button
              onClick={handleLogout}
              className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-white/40 hover:text-white transition-colors px-4 py-2.5 rounded-xl border border-white/10 hover:border-white/30"
            >
              <LogOut className="w-4 h-4" /> Sign Out
            </button>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex gap-2 mb-8 overflow-x-auto pb-2 [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
          {(["leads", "analytics", "staff", "inbox"] as const).map(tab => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`flex items-center gap-2 px-5 py-2 rounded-full text-xs font-bold uppercase tracking-widest border transition-all whitespace-nowrap ${activeTab === tab
                ? "bg-white text-black border-white"
                : "bg-transparent text-white/40 border-white/10 hover:border-white/30 hover:text-white/70"
                }`}
            >
              {tab === "leads" ? <FileText className="w-3.5 h-3.5" /> : tab === "analytics" ? <TrendingUp className="w-3.5 h-3.5" /> : tab === "staff" ? <UserCheck className="w-3.5 h-3.5" /> : <MessageSquare className="w-3.5 h-3.5" />}
              {tab === "leads" ? "All Leads" : tab === "analytics" ? "Analytics" : tab === "staff" ? "Staff Performance" : "Omni-Inbox"}
              {tab === "inbox" && <span className="w-2 h-2 bg-red-500 rounded-full animate-pulse ml-1" />}
            </button>
          ))}
        </div>

        {activeTab === "analytics" && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8"
          >
            <div className="lg:col-span-2 bg-[#0a0a0a] border border-white/5 rounded-[32px] p-6 shadow-xl relative overflow-hidden">
              <div className="flex justify-between items-start mb-6">
                <div>
                  <h3 className="text-xs font-bold uppercase tracking-widest text-white/40 flex items-center gap-2 mb-1">
                    <TrendingUp className="w-4 h-4 text-[#22d3ee]" /> {multiBranchMode ? selectedBranch : "Clinic"} Revenue
                  </h3>
                  <p className="text-3xl font-display font-bold">£134,000</p>
                  <p className="text-xs text-[#22d3ee] font-bold tracking-widest mt-1">+12.4% vs Last Month</p>
                </div>
              </div>
              <div className="h-64 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={revenueData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <XAxis dataKey="name" stroke="#ffffff40" fontSize={10} tickLine={false} axisLine={false} />
                    <YAxis stroke="#ffffff40" fontSize={10} tickLine={false} axisLine={false} tickFormatter={(value) => `£${value / 1000}k`} />
                    <Tooltip
                      cursor={{ fill: 'rgba(255,255,255,0.02)' }}
                      contentStyle={{ backgroundColor: '#0f0f0f', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px' }}
                      itemStyle={{ fontSize: '12px', fontWeight: 'bold' }}
                    />
                    <Bar dataKey="Implement" stackId="a" fill="#3b82f6" radius={[0, 0, 4, 4]} />
                    <Bar dataKey="Invisalign" stackId="a" fill="#c084fc" />
                    <Bar dataKey="Veneers" stackId="a" fill="#22d3ee" radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>

            <div className="bg-[#0a0a0a] border border-white/5 rounded-[32px] p-6 shadow-xl flex flex-col items-center justify-center">
              <h3 className="text-xs font-bold uppercase tracking-widest text-white/40 mb-6 w-full text-left">Treatment Distribution</h3>
              <div className="h-48 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={[
                        { name: 'Implants', value: 45, color: '#3b82f6' },
                        { name: 'Invisalign', value: 35, color: '#c084fc' },
                        { name: 'Veneers', value: 20, color: '#22d3ee' }
                      ]}
                      cx="50%" cy="50%" innerRadius={60} outerRadius={80} paddingAngle={5} dataKey="value" stroke="none"
                    >
                      {
                        [
                          { name: 'Implants', value: 45, color: '#3b82f6' },
                          { name: 'Invisalign', value: 35, color: '#c084fc' },
                          { name: 'Veneers', value: 20, color: '#22d3ee' }
                        ].map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={entry.color} />
                        ))
                      }
                    </Pie>
                    <Tooltip
                      contentStyle={{ backgroundColor: '#0f0f0f', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px' }}
                      itemStyle={{ color: '#fff', fontSize: '12px', fontWeight: 'bold' }}
                    />
                  </PieChart>
                </ResponsiveContainer>
              </div>
              <div className="flex gap-4 mt-4 text-[10px] font-bold uppercase tracking-widest">
                <div className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-blue-500" />Implants</div>
                <div className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-purple-400" />Invisalign</div>
                <div className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-[#22d3ee]" />Veneers</div>
              </div>
            </div>
          </motion.div>
        )}

        {activeTab === "leads" && (<>

          {/* Simple Practical KPI for Execs */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <div className="md:col-span-2 bg-gradient-to-r from-green-500/10 to-transparent border border-white/10 rounded-3xl p-6 md:p-8 flex flex-col justify-center relative overflow-hidden group">
              <div className="absolute -right-20 -top-20 w-64 h-64 bg-green-500/10 blur-[80px] rounded-full pointer-events-none group-hover:bg-green-500/20 transition-colors duration-700" />
              <div className="relative z-10 flex flex-col md:flex-row gap-8 justify-between">
                <div className="flex flex-col flex-1">
                  <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/50 mb-2 flex items-center gap-2">
                    <Check className="w-3.5 h-3.5 text-green-400" /> This Month's Secured Revenue
                  </h3>
                  <div className="flex flex-col w-full">
                    <div className="flex items-end gap-4 mb-3">
                      <p className="text-4xl md:text-6xl font-display font-bold text-white tracking-tighter">
                        £{monthlySecuredRevenue.toLocaleString()}
                      </p>
                      <div className="flex flex-col text-xs font-bold uppercase tracking-widest text-[#22d3ee] mb-1.5 md:mb-2 text-green-400">
                        <span>Target: £50,000</span>
                        <span className={monthlySecuredRevenue >= 50000 ? "text-green-400" : "text-yellow-500"}>
                          {monthlySecuredRevenue >= 50000 ? "Goal Met" : "In Progress"}
                        </span>
                      </div>
                    </div>

                    {/* Tailwind Progress Bar */}
                    <div className="w-full bg-white/10 rounded-full h-2.5 overflow-hidden">
                      <motion.div
                        initial={{ width: 0 }}
                        animate={{ width: `${Math.min((monthlySecuredRevenue / 50000) * 100, 100)}%` }}
                        transition={{ duration: 1.5, ease: "easeOut" }}
                        className={`h-full rounded-full ${monthlySecuredRevenue >= 50000 ? "bg-green-400 shadow-[0_0_10px_rgba(74,222,128,0.5)]" : "bg-gradient-to-r from-orange-500 to-yellow-400 shadow-[0_0_10px_rgba(249,115,22,0.5)]"}`}
                      />
                    </div>
                  </div>
                </div>

                {/* Secondary metric for Pipeline (Unpaid) */}
                <div className="flex flex-col border-l border-white/10 pl-8 justify-center min-w-[200px]">
                  <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/40 mb-2 flex items-center gap-2">
                    <TrendingUp className="w-3.5 h-3.5 text-blue-400" /> This Month's Pipeline
                  </h3>
                  <p className="text-2xl font-display font-bold text-white/80 tracking-tighter mb-1">
                    £{monthlyPipelineRemaining.toLocaleString()}
                  </p>
                  <p className="text-[10px] text-white/40 leading-tight">Potential value awaiting closure this month.</p>
                </div>
              </div>
            </div>

            <div className="bg-[#0f0f0f] border border-white/10 rounded-3xl p-6 md:p-8 flex flex-col justify-center">
              <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/50 mb-3 text-center">
                Quick Action
              </h3>
              <button
                onClick={() => setActiveTab("analytics")}
                className="w-full py-4 px-6 bg-white/5 hover:bg-white/10 border border-white/10 rounded-2xl flex items-center justify-center gap-2 text-xs font-bold uppercase tracking-widest text-white transition-all shadow-sm"
              >
                <TrendingUp className="w-4 h-4 text-[#22d3ee]" /> Deep Analytics
              </button>
            </div>
          </div>


          {/* KPI Cards */}
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5 mb-10">
            {[
              { label: "Confirmed Leads", value: confirmedLeads, icon: Users, color: "text-blue-400", bg: "bg-blue-400/10" },
              { label: "Ghost Patients", value: ghostPatients, icon: MoreHorizontal, color: "text-white/40", bg: "bg-white/5", subValue: ghostLoss > 0 ? `-£${ghostLoss.toLocaleString()}` : "" },
              { label: "Awaiting Response", value: newLeads, icon: TrendingUp, color: "text-green-400", bg: "bg-green-400/10" },
              { label: "Est. Pipeline Value", value: `£${pipelineValue.toLocaleString()}`, icon: TrendingUp, color: "text-yellow-400", bg: "bg-yellow-400/10" },
            ].map((stat, i) => (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
                className="bg-white/5 border border-white/10 p-7 rounded-3xl relative"
              >
                <div className="flex justify-between items-start mb-5">
                  <div className={`p-3 ${stat.bg} rounded-2xl`}>
                    <stat.icon className={`w-5 h-5 ${stat.color}`} />
                  </div>
                </div>
                <div className="flex justify-between items-center mb-1">
                  <p className="text-white/40 text-xs font-bold uppercase tracking-wider leading-none">{stat.label}</p>
                  {stat.subValue && <span className="text-red-500 font-bold text-xs">{stat.subValue}</span>}
                </div>
                <h3 className="text-4xl font-bold">{stat.value}</h3>
              </motion.div>
            ))}
          </div>

          {/* Lead Source — Donut Chart + Insight */}
          <div className="grid lg:grid-cols-3 gap-6 mb-10">
            {/* Donut Chart Card */}
            <div className="bg-white/5 border border-white/10 p-8 rounded-[32px]">
              <h3 className="text-sm font-bold uppercase tracking-widest text-white/60 mb-8 flex items-center gap-2">
                <Globe className="w-4 h-4" /> Leads by Source
              </h3>
              <DonutChart segments={sourceSegments} total={totalLeads} totalValue={pipelineValue + allTimeRevenue} />
            </div>

            {/* Insight Card */}
            <div className="lg:col-span-2 bg-gradient-to-br from-blue-500/10 to-purple-500/5 border border-white/10 p-8 rounded-[32px] flex flex-col justify-between">
              <div>
                <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/30 mb-3">Marketing Intelligence</p>
                <h3 className="text-2xl font-display font-bold mb-4">
                  {totalLeads > 0 ? (
                    <>Top Source: <span className="text-blue-400">{topSource.label}</span></>
                  ) : (
                    "No leads yet"
                  )}
                </h3>
                <p className={`text-sm leading-relaxed max-w-sm ${topSource?.label === "Direct Traffic" && topSource.count === totalLeads && totalLeads > 0 ? "text-red-400 font-medium" : "text-white/50"}`}>
                  {totalLeads > 0
                    ? (topSource?.label === "Direct Traffic" && topSource.count === totalLeads ? "Warning: 100% Reliance on Direct Traffic. You are missing £15,000+ potential revenue from SEO/Ads." : topSourceTip[topSource?.label || ""] ?? "Keep growing your marketing channels.")
                    : "Lead source insights will appear once you receive your first consultation requests."}
                </p>
              </div>

              {/* Mini stats row */}
              <div className="grid grid-cols-3 gap-4 mt-8">
                {sourceSegments.map(seg => (
                  <div key={seg.label} className="bg-white/5 rounded-2xl p-4 text-center">
                    <div className="text-2xl font-bold text-white">{seg.count}</div>
                    <div className="text-[10px] text-white/30 font-bold uppercase tracking-wider mt-1 leading-tight">{seg.label}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Search and Badge Row */}
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6">
            {/* This Month's count badge */}
            {thisMonthNew > 0 ? (
              <div className="inline-flex items-center gap-2 bg-green-400/10 border border-green-400/20 text-green-400 px-4 py-2 rounded-full text-xs font-bold uppercase tracking-wider">
                <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
                {thisMonthNew} new lead{thisMonthNew > 1 ? "s" : ""} this month
              </div>
            ) : <div />}

            {/* Search and Date Picker Row */}
            <div className="flex flex-col md:flex-row items-stretch md:items-center gap-3 w-full md:w-auto">
              {/* Search Bar */}
              <div className="relative flex-1 md:w-64">
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-white/20" />
                <input
                  type="text"
                  placeholder="Search name, treatment..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full bg-white/5 border border-white/10 rounded-2xl py-2.5 pl-11 pr-4 text-sm text-white placeholder:text-white/20 focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all"
                />
              </div>

              {/* Date Picker */}
              <div className="relative flex items-center gap-2">
                <div className="relative">
                  <Calendar className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-white/30 pointer-events-none" />
                  <input
                    type="date"
                    value={selectedDate}
                    onChange={(e) => setSelectedDate(e.target.value)}
                    className="bg-white/5 border border-white/10 rounded-2xl py-2.5 pl-11 pr-10 text-sm text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all appearance-none cursor-pointer [color-scheme:dark]"
                  />
                  {selectedDate && (
                    <button
                      onClick={() => setSelectedDate("")}
                      className="absolute right-3 top-1/2 -translate-y-1/2 p-1 hover:bg-white/10 rounded-full transition-colors"
                    >
                      <X className="w-3.5 h-3.5 text-white/40" />
                    </button>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Kanban Board */}
          <div className="flex justify-between items-center mb-6 mt-12">
            <h2 className="text-xl font-display font-semibold flex items-center gap-3">
              Board
              <span className="bg-white/[0.05] border border-white/10 px-2.5 py-1 rounded-lg text-[11px] font-semibold text-white/50">{totalLeads}</span>
            </h2>
          </div>

          {leads.length === 0 ? (
            <div className="py-24 text-center border border-white/5 rounded-3xl bg-white/[0.01]">
              <FileText className="w-10 h-10 text-white/10 mx-auto mb-4" />
              <p className="text-white/30 text-sm font-medium">No consultation requests yet.</p>
              <p className="text-white/20 text-xs mt-1">They'll appear here as patients submit the form.</p>
            </div>
          ) : (
            <div className="overflow-x-auto pb-8 -mx-6 px-6 md:-mx-10 md:px-10 [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
              <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
                <div className="flex min-w-max">
                  {KANBAN_COLUMNS.map(columnId => {
                    const columnLeads = leads.filter(l => {
                      if (l.status !== columnId) return false;

                      const matchesSearch =
                        l.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                        l.service.toLowerCase().includes(searchTerm.toLowerCase()) ||
                        l.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
                        l.phone.includes(searchTerm);

                      const matchesDate = selectedDate
                        ? (new Date(l.created_at).toISOString().split('T')[0] === selectedDate)
                        : true;

                      return matchesSearch && matchesDate;
                    });

                    return (
                      <KanbanColumn
                        key={columnId}
                        columnId={columnId}
                        columnLeads={columnLeads}
                        setDepositModal={setDepositModal}
                        setSelectedLead={setSelectedLead}
                        updateStatus={updateStatus}
                        STAFF_LIST={STAFF_LIST}
                        updateAssignedTo={updateAssignedTo}
                        timeAgo={timeAgo}
                      />
                    );
                  })}
                </div>
              </DndContext>
            </div>
          )}
        </>)}

        {/* ── Omni-Channel Inbox Tab ───────────────────────────────── */}
        {activeTab === "inbox" && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="grid lg:grid-cols-12 gap-6 h-[720px]"
          >
            {/* Conversations List */}
            <div className="lg:col-span-4 bg-white/[0.03] backdrop-blur-xl border border-white/10 rounded-[40px] overflow-hidden flex flex-col">
              <div className="p-8 border-b border-white/10">
                <h3 className="text-xl font-display font-bold text-white mb-2 uppercase tracking-tight">Messages</h3>
                <p className="text-white/30 text-[10px] font-bold uppercase tracking-[0.2em]">Unified Channel Feed</p>
              </div>
              <div className="flex-1 overflow-y-auto">
                {mockChats.map((chat) => (
                  <button
                    key={chat.id}
                    onClick={() => setSelectedChat(chat.id)}
                    className={`w-full p-6 flex gap-4 text-left border-b border-white/5 transition-all hover:bg-white/[0.05] ${selectedChat === chat.id ? 'bg-white/[0.08]' : ''}`}
                  >
                    <div className="w-12 h-12 rounded-2xl bg-white/10 flex items-center justify-center font-bold text-primary relative shrink-0">
                      {chat.avatar}
                      {chat.source === "Instagram" && <Instagram className="w-4 h-4 absolute -bottom-1 -right-1 text-pink-500 fill-pink-500 bg-black rounded-full p-0.5" />}
                      {chat.source === "Kakao" && <MessageCircle className="w-4 h-4 absolute -bottom-1 -right-1 text-yellow-500 fill-yellow-500 bg-black rounded-full p-0.5" />}
                      {chat.source === "Website" && <Globe className="w-4 h-4 absolute -bottom-1 -right-1 text-blue-400 fill-blue-400 bg-black rounded-full p-0.5" />}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex justify-between items-center mb-1">
                        <span className="text-sm font-bold text-white uppercase tracking-tight">{chat.recipient}</span>
                        <span className="text-[10px] text-white/20 font-bold">{chat.time}</span>
                      </div>
                      <p className={`text-xs truncate ${chat.unread ? 'text-primary font-bold' : 'text-white/40 font-medium'}`}>{chat.lastMsg}</p>
                    </div>
                  </button>
                ))}
              </div>
            </div>

            {/* Chat Window */}
            <div className="lg:col-span-8 bg-white/[0.03] backdrop-blur-xl border border-white/10 rounded-[40px] overflow-hidden flex flex-col">
              {selectedChat !== null ? (
                <>
                  <div className="p-8 border-b border-white/10 flex justify-between items-center">
                    <div className="flex items-center gap-4">
                      <div className="w-12 h-12 rounded-2xl bg-white/10 flex items-center justify-center font-bold text-primary">
                        {mockChats[selectedChat!].avatar}
                      </div>
                      <div>
                        <h4 className="text-lg font-display font-bold text-white uppercase tracking-tight">{mockChats[selectedChat!].recipient}</h4>
                        <div className="flex items-center gap-2">
                          <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                          <span className="text-[10px] text-white/30 font-bold uppercase tracking-widest">Active on {mockChats[selectedChat!].source}</span>
                        </div>
                      </div>
                    </div>
                    <div className="flex gap-2">
                      <button className="p-3 bg-white/5 rounded-xl hover:bg-white/10 transition-colors"><MoreHorizontal className="w-5 h-5 text-white/40" /></button>
                    </div>
                  </div>

                  <div className="flex-1 overflow-y-auto p-8 space-y-6">
                    {mockChats[selectedChat!].messages.map((m, i) => (
                      <div key={i} className={`flex ${m.sender === 'staff' ? 'justify-end' : 'justify-start'}`}>
                        <div className={`max-w-[70%] p-5 rounded-3xl text-sm font-medium leading-relaxed ${m.sender === 'staff' ? 'bg-primary text-black rounded-tr-none' : 'bg-white/5 text-white/80 rounded-tl-none border border-white/10'}`}>
                          {m.text}
                        </div>
                      </div>
                    ))}
                  </div>

                  <div className="p-8 border-t border-white/10 space-y-4">
                    <div className="flex gap-2">
                      {["Price Enquiry", "Schedule Visit", "Preparation Help"].map(template => (
                        <button key={template} className="text-[10px] font-bold uppercase tracking-widest text-white/30 hover:text-primary hover:bg-primary/10 border border-white/10 px-4 py-2 rounded-full transition-all">
                          {template}
                        </button>
                      ))}
                    </div>
                    <div className="relative">
                      <input
                        type="text"
                        value={replyText}
                        onChange={(e) => setReplyText(e.target.value)}
                        placeholder="Type your message here..."
                        className="w-full bg-white/5 border border-white/10 rounded-2xl py-4 pl-6 pr-16 text-sm text-white focus:outline-none focus:ring-2 focus:ring-primary/50 transition-all placeholder:text-white/10"
                      />
                      <button className="absolute right-2 top-2 p-2 bg-primary text-black rounded-xl hover:brightness-110 active:scale-90 transition-all">
                        <Send className="w-5 h-5" />
                      </button>
                    </div>
                  </div>
                </>
              ) : (
                <div className="flex-1 flex flex-col items-center justify-center text-center p-12 opacity-30">
                  <MessageSquare className="w-16 h-16 mb-6" />
                  <p className="text-xl font-display font-bold uppercase tracking-tight text-white mb-2">Select a Conversation</p>
                  <p className="text-sm font-medium">All your patient communication in one unified source.</p>
                </div>
              )}
            </div>
          </motion.div>
        )}

        {/* ── Staff Performance Tab ─────────────────────────────────── */}
        {activeTab === "staff" && (() => {
          const assigned = leads.filter(l => l.assigned_to);
          const staffNames = [...new Set(assigned.map(l => l.assigned_to!))].sort();

          const stats = staffNames.map(name => {
            const myLeads = leads.filter(l => l.assigned_to === name);
            const contacted = myLeads.filter(l => l.first_contact_at);
            const avgHrs = contacted.length > 0
              ? contacted.reduce((sum, l) => {
                const ms = new Date(l.first_contact_at!).getTime() - new Date(l.created_at).getTime();
                return sum + ms / 3600000;
              }, 0) / contacted.length
              : null;
            const converted = myLeads.filter(l => ["Consultation Booked", "Visited", "Treatment Started"].includes(l.status));
            const convRate = myLeads.length > 0 ? Math.round((converted.length / myLeads.length) * 100) : 0;
            return { name, total: myLeads.length, avgHrs, convRate };
          });

          return (
            <div className="bg-white/5 border border-white/10 rounded-3xl overflow-hidden">
              <div className="p-7 border-b border-white/10">
                <h2 className="text-lg font-bold flex items-center gap-2">
                  <UserCheck className="w-5 h-5 text-white/50" /> Staff Performance
                </h2>
                <p className="text-white/30 text-sm mt-1">Assign leads to staff using the dropdowns in All Leads tab</p>
              </div>
              {stats.length === 0 ? (
                <div className="py-20 text-center">
                  <UserCheck className="w-10 h-10 text-white/10 mx-auto mb-4" />
                  <p className="text-white/30 text-sm">No staff assigned yet. Go to All Leads and assign leads to team members.</p>
                </div>
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full text-left">
                    <thead>
                      <tr className="border-b border-white/10 bg-white/[0.02]">
                        {["Staff Member", "Leads Assigned", "Avg Response Time", "Conversion Rate", "Performance"].map(h => (
                          <th key={h} className="px-6 py-4 text-[10px] font-bold text-white/30 uppercase tracking-wider">{h}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-white/[0.06]">
                      {stats.map(s => (
                        <tr key={s.name} className="hover:bg-white/[0.03] transition-colors">
                          <td className="px-6 py-5 font-bold text-sm">{s.name}</td>
                          <td className="px-6 py-5 text-sm text-white/60">{s.total}</td>
                          <td className="px-6 py-5 text-sm">
                            {s.avgHrs !== null ? (
                              <span className={s.avgHrs < 1 ? "text-green-400" : s.avgHrs < 4 ? "text-yellow-400" : "text-red-400"}>
                                {s.avgHrs < 1 ? `${Math.round(s.avgHrs * 60)}m` : `${s.avgHrs.toFixed(1)}h`}
                              </span>
                            ) : <span className="text-white/20">—</span>}
                          </td>
                          <td className="px-6 py-5">
                            <span className={`text-sm font-bold ${s.convRate >= 60 ? "text-green-400" : s.convRate >= 30 ? "text-yellow-400" : "text-red-400"
                              }`}>{s.convRate}%</span>
                          </td>
                          <td className="px-6 py-5">
                            <div className="w-32 bg-white/10 rounded-full h-1.5">
                              <div
                                className={`h-1.5 rounded-full ${s.convRate >= 60 ? "bg-green-400" : s.convRate >= 30 ? "bg-yellow-400" : "bg-red-400"
                                  }`}
                                style={{ width: `${s.convRate}%` }}
                              />
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          );
        })()}

      </div>
    </div>
  );
}
