import React, { useEffect, useState, useMemo } from "react";
// Deploy Trigger: Rollback Verification
import { motion } from "motion/react";
import {
  Users, ArrowLeft, MoreHorizontal,
  LogOut, TrendingUp, RefreshCw, FileText,
  Search, Globe, Star, UserCheck, Calendar, X, Filter, List, BarChart2,
  Presentation, Play, ChevronRight, Check, XCircle,
  MessageSquare, Send, Sparkles, Layout,
  ArrowRight, ShieldCheck, Zap, Settings, SlidersHorizontal, Building, Save, Plus, Trash2, Camera, Palette, CreditCard,
  Mail, UserPlus, Loader2, Clock, Copy, Shield,
  Link2, AlertTriangle, MapPin, ChevronDown, Instagram, MessageCircle, Link as LinkIcon, Monitor, Stethoscope
} from 'lucide-react';
import { Link, useNavigate } from "react-router-dom";
import { supabase, type ConsultationRequest, type Profile, type Invitation } from "../lib/supabase";
import { useAuth } from "../context/AuthContext";
import { trackEvent } from "../lib/analytics";
import { generateDailyBriefing } from "../lib/ai-assistant-service";
import { SERVICE_CONVERSION_VALUES } from "../lib/constants";
import { AutoTaggingModal } from "./dashboard/shared/AutoTaggingModal";
import { AnimatePresence } from "motion/react";
import { DndContext, closestCenter, KeyboardSensor, PointerSensor, useSensor, useSensors, DragEndEvent, useDroppable } from '@dnd-kit/core';
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { ActivityLog } from './ActivityLog';
import { CSVImportZone } from './CSVImportZone';
import { TreatmentSettings } from './TreatmentSettings';
import { StaffROILeaderboard } from './dashboard/tabs/StaffROILeaderboard';
import { RevenueMetrics } from './dashboard/RevenueMetrics';
import { UpsellOpportunities } from './dashboard/UpsellOpportunities';
import { ReputationROIChart } from './dashboard/ReputationROIChart';
import { PTConsultationMode } from './dashboard/PTConsultationMode';
import { TreatmentCard } from './TreatmentCard';
import { TreatmentDetailDrawer } from './TreatmentDetailDrawer';
import { DashboardKPIs } from './DashboardKPIs';
import { RevenueForecastChart } from './dashboard/RevenueForecastChart';
import { PatientTimeline, TimelineEvent } from './dashboard/PatientTimeline';
import { RecoveryConcierge } from './dashboard/RecoveryConcierge';
import { DashboardHeader } from "./dashboard/layout/DashboardHeader";
import { SettingsDrawer } from "./dashboard/SettingsDrawer";
import { ZeroDashboardView } from "./dashboard/ZeroDashboardView";
import { ExpertModeDrawer } from "./dashboard/ExpertModeDrawer";

// Assets for PT Mode (Generated by AntiGravity)
const PT_ASSETS: Record<string, { image: string; title: string; benefit: string; script: string }> = {
  "Dental Implants": {
    image: "/brain/0774c8b3-dc9c-4ab9-82fe-cc27c1e404a8/dental_implant_3d_visual_1772134009341.png",
    title: "Precision Implantology",
    benefit: "Implants look and function like natural teeth, preserving your jawbone and facial structure.",
    script: "As you can see from our 3D analysis, we precisely map your nerves and bone structure for a perfect placement. This investment restores your smile for a lifetime."
  },
  "Veneers": {
    image: "/brain/0774c8b3-dc9c-4ab9-82fe-cc27c1e404a8/veneer_before_after_mockup_1772134023178.png",
    title: "Hollywood Smile Makeover",
    benefit: "Ultra-thin porcelain veneers correct shape, color, and alignment in as little as two visits.",
    script: "Look at the transformation. Veneers are an art form that creates total facial harmony. It's the gold standard for achieving a celebrity-level smile with minimal invasion."
  },
  "Invisalign / Aligners": {
    image: "/brain/0774c8b3-dc9c-4ab9-82fe-cc27c1e404a8/invisalign_simulation_ui_1772134037487.png",
    title: "SmartSmile Aligner Simulation",
    benefit: "Straighten your teeth invisibly with removable aligners and see your final result before you start.",
    script: "Notice how your teeth will shift over the next 6 months. We can project your exact final result today. It's the most discreet and comfortable way to achieve perfection."
  }
};

// Removed PresentationOverlay as PT Mode is now strictly client-facing at /pt/:id

function useDebounce<T>(value: T, delay: number): T {
  const [debouncedValue, setDebouncedValue] = useState<T>(value);
  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedValue(value);
    }, delay);
    return () => clearTimeout(handler);
  }, [value, delay]);
  return debouncedValue;
}

function timeAgo(dateStr: string): string {

  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "Just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  if (days < 7) return `${days}d ago`;
  return new Date(dateStr).toLocaleDateString("en-GB", { day: "numeric", month: "short" });
}


const STATUS_COLORS: Record<string, string> = {
  "New Lead": "text-[#C5A059] border-[#C5A059]/40 bg-[#C5A059]/10",
  "Qualified": "text-purple-400 border-purple-400/40 bg-transparent",
  "Proposal Sent": "text-yellow-400 border-yellow-400/40 bg-yellow-400/10",
  "Closed Won": "text-[#87A96B] border-[#87A96B]/40 bg-[#87A96B]/10",
  "Abandoned": "text-gray-400 border-black/10 bg-black/5",
  "Future Pipeline": "text-blue-400 border-blue-400/40 bg-blue-400/10",
};

// Static staff list removed. Using dynamic list from teamMembers and leads instead.

export interface OmniMessage {
  id: string;
  clinic_id?: string;
  lead_id: string | null;
  sender_raw: string;
  channel: 'whatsapp' | 'sms' | 'instagram' | 'website';
  content: string;
  direction: 'inbound' | 'outbound';
  is_read: boolean;
  created_at: string;
}

export interface OmniThread {
  id: string;
  recipient: string;
  source: string;
  channel: string;
  avatar: string;
  lastMsg: string;
  time: string;
  unread: boolean;
  messages: OmniMessage[];
}
// ── Animated SVG Donut Chart ─────────────────────────────────────────────
interface DonutSegment {
  label: string;
  count: number;
  color: string;
  hex: string;
}

function DonutChart({ segments, total, totalValue }: { segments: DonutSegment[]; total: number; totalValue: number }) {
  const [animated, setAnimated] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => setAnimated(true), 200);
    return () => clearTimeout(timer);
  }, []);

  const size = 180;
  const strokeWidth = 28;
  const radius = (size - strokeWidth) / 2;
  const circumference = 2 * Math.PI * radius;
  const cx = size / 2;
  const cy = size / 2;

  // Build dash segments
  let cumulativePercent = 0;
  const segmentElements = segments.map((seg, i) => {
    const percent = total > 0 ? seg.count / total : 0;
    const dashArray = circumference * percent;
    const dashOffset = circumference * (1 - cumulativePercent);
    cumulativePercent += percent;

    return (
      <circle
        key={seg.label}
        cx={cx}
        cy={cy}
        r={radius}
        fill="none"
        stroke={seg.hex}
        strokeWidth={strokeWidth}
        strokeDasharray={`${animated ? dashArray : 0} ${circumference}`}
        strokeDashoffset={dashOffset}
        strokeLinecap="butt"
        transform={`rotate(-90 ${cx} ${cy})`}
        style={{ transition: `stroke-dasharray 0.8s ease ${i * 0.15}s` }}
      />
    );
  });

  return (
    <div className="flex flex-col items-center">
      <div className="relative">
        <svg width={size} height={size}>
          {/* Background ring */}
          <circle
            cx={cx} cy={cy} r={radius}
            fill="none"
            stroke="rgba(255,255,255,0.05)"
            strokeWidth={strokeWidth}
          />
          {segmentElements}
        </svg>
        {/* Centre label */}
        <div className="absolute inset-0 flex flex-col items-center justify-center gap-1 mt-1">
          <div className="flex flex-col items-center">
            <span className="text-xl font-bold text-gray-900 leading-none">{total}</span>
            <span className="text-[9px] text-gray-500 uppercase tracking-widest font-bold">Leads</span>
          </div>
          <div className="w-8 h-px bg-white/20 my-0.5" />
          <div className="flex flex-col items-center">
            <span className="text-[15px] font-bold text-[#87A96B] leading-none" data-hj-suppress>£{(totalValue / 1000).toFixed(1)}k</span>
            <span className="text-[9px] text-gray-500 uppercase tracking-widest font-bold">Value</span>
          </div>
        </div>
      </div>

      {/* Legend */}
      <div className="mt-6 w-full space-y-3">
        {segments.map((seg) => {
          const pct = total > 0 ? Math.round((seg.count / total) * 100) : 0;
          return (
            <div key={seg.label} className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="w-2.5 h-2.5 rounded-full flex-shrink-0" style={{ background: seg.hex }} />
                <span className="text-[11px] text-gray-500 font-medium">{seg.label}</span>
              </div>
              <span className="text-[11px] font-bold text-gray-900/80">
                {seg.count} <span className="text-gray-400">({pct}%)</span>
              </span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ── Notification Dropdown ────────────────────────────────────────────────
function NotificationDropdown({ notifications, onClose, onDismiss }: { notifications: any[]; onClose: () => void; onDismiss: (id: string) => void }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10, scale: 0.95 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, y: 10, scale: 0.95 }}
      className="absolute top-full right-0 mt-4 w-80 bg-white border border-black/10 rounded-3xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] p-6 z-[100] backdrop-blur-xl"
    >
      <div className="flex justify-between items-center mb-6">
        <h3 className="text-xs font-bold text-gray-900 uppercase tracking-widest">Recent Activity</h3>
        <button onClick={onClose} className="p-1 hover:bg-black/5 rounded-lg text-gray-500">
          <X className="w-4 h-4" />
        </button>
      </div>
      <div className="space-y-4 max-h-[300px] overflow-y-auto pr-2 custom-scrollbar">
        {notifications.length === 0 ? (
          <p className="text-[10px] text-gray-400 text-center py-8 italic">No new activity</p>
        ) : (
          notifications.map((n) => (
            <div key={n.id} className="relative p-4 bg-white/[0.03] border border-black/5 rounded-2xl group transition-all hover:bg-white/[0.05]">
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  onDismiss(n.id);
                }}
                className="absolute top-3 right-3 p-1 rounded-md text-gray-400 hover:text-gray-900 hover:bg-black/5 transition-colors"
                title="Dismiss"
              >
                <X className="w-3.5 h-3.5" />
              </button>
              <p className="text-[11px] text-gray-900/80 leading-relaxed mb-2 pr-6">{n.message}</p>
              <span className="text-[8px] font-bold text-[#87A96B] uppercase tracking-tighter">{n.time}</span>
            </div>
          ))
        )}
      </div>
    </motion.div>
  );
}

// ── Waitlist Panel ───────────────────────────────────────────────────────
function WaitlistPanel({
  isOpen,
  onClose,
  waitlist,
  onInvite,
  onBroadcast,
  isBroadcasting
}: {
  isOpen: boolean;
  onClose: () => void;
  waitlist: ConsultationRequest[];
  onInvite: (id: string) => void;
  onBroadcast: () => void;
  isBroadcasting: boolean;
}) {
  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ x: 400 }}
          animate={{ x: 0 }}
          exit={{ x: 400 }}
          transition={{ type: "spring", damping: 25, stiffness: 200 }}
          className="fixed top-0 right-0 h-full w-[380px] bg-white border-l border-black/10 shadow-[-20px_0_50px_rgba(0,0,0,0.5)] z-[101] p-10 backdrop-blur-3xl overflow-y-auto custom-scrollbar"
        >
          <div className="flex justify-between items-center mb-10">
            <div>
              <h2 className="text-2xl font-display font-bold text-gray-900">Smart Waitlist</h2>
              <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mt-1">Gap Filling Automation</p>
            </div>
            <button onClick={onClose} className="p-3 bg-black/5 hover:bg-black/5 rounded-2xl text-gray-900 transition-all">
              <X className="w-6 h-6" />
            </button>
          </div>

          <div className="space-y-6 mb-24">
            <div className="p-6 bg-[#87A96B]/5 border border-[#87A96B]/20 rounded-3xl group transition-all">
              <p className="text-[10px] font-bold text-[#87A96B] uppercase tracking-[0.2em] mb-3 leading-none">Intelligence Pack</p>
              <h3 className="text-lg font-bold text-gray-900 mb-2 underline decoration-[#87A96B]/30 underline-offset-4">1-Click Gap Filler</h3>
              <p className="text-xs text-gray-500 leading-relaxed mb-6">We found a 2:00 PM slot tomorrow. Notify all matching waitlist patients?</p>
              <button
                onClick={onBroadcast}
                disabled={isBroadcasting}
                className="w-full py-4 bg-[#87A96B] text-black font-black uppercase tracking-widest text-[11px] rounded-2xl hover:scale-[1.02] transition-transform active:scale-95 shadow-[0_0_30px_rgba(0,255,204,0.3)] disabled:opacity-50 flex items-center justify-center gap-2"
              >
                {isBroadcasting ? <Loader2 className="w-4 h-4 animate-spin" /> : null}
                {isBroadcasting ? "Broadcasting..." : "Broadcast Availability"}
              </button>
            </div>

            <div className="space-y-3">
              <div className="flex justify-between items-center mb-1 ml-1">
                <h4 className="text-[9px] font-bold text-gray-400 uppercase tracking-widest">Priority Waitlist</h4>
                <span className="text-[9px] font-bold text-gray-400 bg-black/5 px-2 py-0.5 rounded-full">{waitlist.length} waiting</span>
              </div>

              <AnimatePresence>
                {waitlist.length === 0 ? (
                  <p className="text-[10px] text-gray-400 italic pb-4">No patients currently on the waitlist.</p>
                ) : (
                  waitlist.map(w => (
                    <motion.div
                      key={w.id}
                      layout
                      initial={{ opacity: 0, y: 10, scale: 0.95 }}
                      animate={{ opacity: 1, y: 0, scale: 1 }}
                      exit={{ opacity: 0, scale: 0.9, transition: { duration: 0.2 } }}
                      className="p-5 bg-white/[0.02] border border-black/5 rounded-2xl flex justify-between items-center group hover:bg-white/[0.04] transition-all"
                    >
                      <div>
                        <h5 className="font-bold text-gray-900 text-sm truncate max-w-[120px]">{w.name}</h5>
                        <p className="text-[10px] text-gray-400 font-medium truncate max-w-[120px]">{w.service}</p>
                      </div>
                      <div className="flex flex-col items-end gap-1">
                        <span className="text-[10px] font-bold text-[#87A96B]/70 bg-[#87A96B]/10 px-2 py-0.5 rounded border border-[#87A96B]/20">
                          £{(SERVICE_CONVERSION_VALUES[w.service] || 1000).toLocaleString()}
                        </span>
                        <div className="flex items-center gap-2 mt-1">
                          <span className="text-[8px] font-bold text-[#87A96B]/60 uppercase">{timeAgo(w.created_at)}</span>
                          <button
                            onClick={() => onInvite(w.id)}
                            className="text-[9px] font-bold text-gray-900 opacity-0 group-hover:opacity-100 transition-opacity uppercase tracking-tighter underline ml-1"
                          >
                            Invite
                          </button>
                        </div>
                      </div>
                    </motion.div>
                  ))
                )}
              </AnimatePresence>
            </div>
          </div>

          <div className="absolute bottom-6 left-6 right-6">
            <div className="flex items-center gap-3 p-4 bg-black/5 rounded-2xl border border-black/10">
              <ShieldCheck className="w-5 h-5 text-gray-400 shrink-0" strokeWidth={1.5} />
              <p className="text-[9px] text-gray-400 font-medium leading-tight select-none">HIPAA Compliant Automation Protocol active for all patient communications.</p>
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

// ── Kanban Drag & Drop Wrapper ───────────────────────────────────────────

const SortableLeadCard = React.memo(function SortableLeadCard({
  id,
  lead,
  setDepositModal,
  setSelectedLead,
  updateStatus,
  STAFF_LIST,
  updateAssignedTo,
  timeAgo,
  clinic: clinicData,
  onAddToWaitlist,
  onOpenPTMode

}: {
  id: string;
  lead: ConsultationRequest;
  setDepositModal: any;
  setSelectedLead: any;
  updateStatus: any;
  STAFF_LIST: string[];
  updateAssignedTo: any;
  timeAgo: any;
  clinic: any;
  onAddToWaitlist?: (id: string) => void;
  onOpenPTMode: (lead: ConsultationRequest) => void;
}) {
  const [timeLeft, setTimeLeft] = useState<number>(15 * 60);

  useEffect(() => {
    // Initial calculate based on lead.created_at
    const created = new Date(lead.created_at).getTime();
    const now = Date.now();
    const diffSec = Math.floor((created + 15 * 60 * 1000 - now) / 1000);
    setTimeLeft(Math.max(0, diffSec));

    const interval = setInterval(() => {
      setTimeLeft(prev => Math.max(0, prev - 1));
    }, 1000);
    return () => clearInterval(interval);
  }, [lead.created_at]);

  const formatTimer = (sec: number) => {
    const m = Math.floor(sec / 60);
    const s = sec % 60;
    return `${m}:${s < 10 ? '0' : ''}${s}`;
  };

  const getTimerColor = (sec: number) => {
    if (sec <= 0) return "text-red-500 font-black animate-pulse";
    if (sec < 300) return "text-red-500 font-bold animate-pulse";
    if (sec < 600) return "text-yellow-400 font-bold";
    return "text-gray-500 font-bold";
  };

  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging
  } = useSortable({ id });

  const [isSendingEmail, setIsSendingEmail] = useState(false);
  const [isExiting, setIsExiting] = useState(false);

  const handleSendEmail = async (e: React.MouseEvent) => {
    e.stopPropagation();
    setIsSendingEmail(true);
    try {
      const response = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/send-pt-link`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}`
        },
        body: JSON.stringify({
          lead_id: lead.id,
          name: lead.name,
          email: lead.email,
          service: lead.service,
          origin: window.location.origin,
          clinic_name: clinicData?.name,
          clinic_logo: clinicData?.logo_url,
          brand_color: clinicData?.brand_color,
          clinic_phone: clinicData?.phone,
          clinic_address: clinicData?.address,
          clinic_email: clinicData?.email
        })
      });

      if (!response.ok) throw new Error("Failed to send email");
      alert(`PT Link successfully sent to ${lead.email}!`);
    } catch (err) {
      console.error(err);
      alert("Error sending email. Please try again.");
    } finally {
      setIsSendingEmail(false);
    }
  };

  const handleWaitlistClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    setIsExiting(true); // Trigger exit animation state
    // Wait for exit animation to complete before removing from DOM
    setTimeout(() => {
      onAddToWaitlist?.(lead.id);
    }, 400);
  };

  const isVIP = lead.name.toLowerCase().includes("vip");
  const timeLimit = isVIP ? 15 * 60 * 1000 : 86400000;
  const isOverdue = (lead.status === "New Lead" || lead.status === "Future Pipeline") && (Date.now() - new Date(lead.created_at).getTime()) > timeLimit;

  const style = {
    transform: CSS.Transform.toString(transform),
    transition: isDragging ? transition : "transform 400ms cubic-bezier(0.18, 0.67, 0.6, 1.22)", // Spring effect on drop
    zIndex: isDragging ? 50 : 1,
  };

  return (
    <div ref={setNodeRef} style={style} className="mb-3 outline-none">
      <motion.div
        layout
        initial={{ opacity: 1, scale: 1 }}
        whileHover={{ scale: 1.02 }}
        animate={isExiting ? { opacity: 0, scale: 0.8, x: 50, filter: "blur(4px)" } : {
          scale: isDragging ? 1.02 : 1,
          rotate: isDragging ? 2 : 0,
          boxShadow: isDragging
            ? "0 30px 60px rgba(0,0,0,0.6), inset 0 1px 0 rgba(255,255,255,0.1)"
            : isOverdue
              ? "0 0 15px rgba(230,57,70,0.6)"
              : "0 10px 30px -10px rgba(0,0,0,0.4), inset 0 0 0 1px rgba(0,0,0,0.05)",
          opacity: isDragging ? 0.95 : 1,
          backgroundColor: isDragging ? "rgba(255,255,255,0.95)" : "rgba(255,255,255,1)",
          y: isDragging ? -10 : 0
        }}
        transition={{ type: "spring", stiffness: 80, damping: 20 }}
        className={`rounded-2xl p-4 relative group focus:outline-none transition-all
          ${isDragging ? 'border-emerald-500/30 cursor-grabbing bg-[#0A0F1E]/80 backdrop-blur-3xl shadow-2xl' :
            isOverdue ? 'border-[#E63946]/50 hover:border-[#E63946]/80 cursor-grab animate-pulse bg-white/5 backdrop-blur-xl' :
              'border-white/10 hover:border-emerald-500/20 cursor-grab hover:bg-white/[0.08] bg-white/5 backdrop-blur-xl shadow-lg'
          }`}
      >
        {/* Drag Handle Area */}
        <div {...attributes} {...listeners} className="absolute inset-0 z-0 outline-none rounded-2xl" />

        {/* Content Area - Minimal Data Density (Hick's Law) */}
        <div className="relative z-10 pointer-events-none">
          <div className="flex justify-between items-start mb-3">
            <div>
              <h4 className="font-bold text-[14px] tracking-[-0.02em] text-white truncate mr-2 flex items-center gap-2" data-hj-suppress>
                {lead.name}
              </h4>
              <p className="text-[10px] text-zinc-400 font-medium mt-1 lowercase">Joined {timeAgo(lead.created_at)}</p>
            </div>

            <div className="flex flex-col items-end gap-1">
              <span className="text-[14px] font-black text-[#10B981] tracking-tight tabular-nums">
                £{(lead.potential_value ? lead.potential_value : (1000)).toLocaleString()}
              </span>
              {/* Urgent Tag (Terracotta) */}
              {isOverdue && (
                <span className="text-[9px] font-bold text-[#FF3B30] bg-[#FF3B30]/10 border border-[#FF3B30]/20 px-1.5 py-0.5 rounded uppercase tracking-wider flex items-center gap-1">
                  <AlertTriangle className="w-2 h-2" strokeWidth={1.5} /> Urgent
                </span>
              )}
            </div>
          </div>

          {/* Tags */}
          <div className="flex flex-wrap gap-1 mb-1 items-center">
            {lead.intent_score && (
              <span className={`text-[9px] font-black px-1.5 py-0.5 rounded uppercase tracking-wider flex items-center gap-1 border ${lead.intent_score >= 80 ? 'text-[#00FFA3] bg-[#00FFA3]/10 border-[#00FFA3]/20' :
                lead.intent_score >= 50 ? 'text-[#C5A059] bg-[#C5A059]/10 border-[#C5A059]/20' :
                  'text-[#FF3B30] bg-[#FF3B30]/10 border-[#FF3B30]/20'
                }`}>
                <Sparkles className="w-2 h-2" /> AI {lead.intent_score}%
              </span>
            )}
            <span className="text-[10px] font-bold text-zinc-300 bg-white/5 px-2 py-0.5 rounded-md border border-white/10 uppercase tracking-tighter">
              {lead.service}
            </span>
            {lead.appointment_date && !isNaN(new Date(lead.appointment_date).getTime()) && (
              <span className="text-[10px] font-bold text-[#87A96B] bg-emerald-500/10 px-2 py-0.5 rounded-md border border-emerald-500/20">
                {new Date(lead.appointment_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })}
              </span>
            )}
            {lead.status === "Consultation Done" && (
              <span className="text-[10px] font-bold text-[#0A0F1E] bg-[#10B981] px-2 py-0.5 rounded-md shadow-[0_0_15px_rgba(16,185,129,0.4)]">
                Consulted
              </span>
            )}
          </div>
          <div className="mt-4 pt-4 border-t border-white/[0.05] flex justify-between items-center pointer-events-auto opacity-0 group-hover:opacity-100 transition-all duration-300">
            <div className="flex gap-2 w-full justify-end">
              {lead.status === "New Lead" && (
                <button
                  onClick={handleWaitlistClick}
                  className="px-3 py-1.5 text-zinc-400 hover:text-white bg-white/5 hover:bg-white/10 rounded-xl transition-all border border-white/10 text-[10px] font-bold uppercase tracking-widest flex items-center gap-1.5 self-center mr-1"
                  title="Move to Waitlist"
                >
                  <Users className="w-3 h-3" strokeWidth={1.5} /> Waitlist
                </button>
              )}
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  onOpenPTMode(lead);
                }}
                className="p-1.5 text-emerald-400 hover:text-emerald-300 bg-emerald-500/10 hover:bg-emerald-500/20 rounded-lg transition-all border border-emerald-500/20 shadow-lg shadow-emerald-500/5"
                title="Open Tablet PT Consultation Mode"
              >
                <Monitor className="w-3.5 h-3.5" strokeWidth={1.5} />
              </button>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  setSelectedLead(lead);
                }}
                className="p-1.5 text-zinc-400 hover:text-white bg-white/5 hover:bg-white/10 rounded-lg transition-all border border-white/10"
                title="View Inquiry details"
              >
                <FileText className="w-3.5 h-3.5" strokeWidth={1.5} />
              </button>
              <button
                onClick={handleSendEmail}
                disabled={isSendingEmail}
                className="p-1.5 text-[#87A96B] hover:text-[#87A96B]/80 bg-[#87A96B]/10 hover:bg-[#87A96B]/20 rounded-lg transition-all border border-[#87A96B]/20 disabled:opacity-50"
                title="Send PT Link via Email"
              >
                {isSendingEmail ? <RefreshCw className="w-3.5 h-3.5 animate-spin text-[#87A96B]" strokeWidth={1.5} /> : <Send className="w-3.5 h-3.5" strokeWidth={1.5} />}
              </button>
            </div>
          </div>
        </div>
      </motion.div>
    </div>
  );
}, (prev, next) => prev.lead === next.lead && prev.clinic === next.clinic && prev.id === next.id);

function KanbanColumn({
  columnId,
  columnLeads,
  setDepositModal,
  setSelectedLead,
  updateStatus,
  STAFF_LIST,
  updateAssignedTo,
  timeAgo,
  clinic,
  onAddToWaitlist,
  selectedDate,
  onOpenPTMode
}: {
  columnId: string;
  columnLeads: ConsultationRequest[];
  setDepositModal: any;
  setSelectedLead: any;
  updateStatus: any;
  STAFF_LIST: string[];
  updateAssignedTo: any;
  timeAgo: any;
  clinic: any;
  onAddToWaitlist?: (id: string) => void;
  selectedDate: string;
  onOpenPTMode: (lead: ConsultationRequest) => void;
}) {
  const { setNodeRef } = useDroppable({ id: columnId });

  // Sort logic for specific columns
  const sortedLeads = useMemo(() => {
    if (columnId === "Booked") {
      return [...columnLeads].sort((a, b) => {
        if (!a.appointment_date) return 1;
        if (!b.appointment_date) return -1;
        return new Date(a.appointment_date).getTime() - new Date(b.appointment_date).getTime();
      });
    }
    if (columnId === "Treatment Started") {
      return [...columnLeads].sort((a, b) => {
        if (!a.treated_at) return 1;
        if (!b.treated_at) return -1;
        return new Date(b.treated_at).getTime() - new Date(a.treated_at).getTime(); // Newest treatment first
      });
    }
    return columnLeads;
  }, [columnId, columnLeads]);

  return (
    <div className={`w-[290px] shrink-0 flex flex-col h-[calc(100vh-280px)] pr-4 mr-4 last:border-r-0 last:mr-0 last:pr-0 transition-all duration-500`}>
      <div className="flex flex-col mb-6 px-1">
        <div className="flex justify-between items-center mb-1">
          <h3 className="text-label flex items-center gap-2">
            {columnId}
            <span className="text-[10px] font-bold opacity-30 bg-black/5 px-2 py-0.5 rounded-md">{columnLeads.length}</span>
          </h3>
        </div>
        {/* Pipeline Value Header (Apple-Style Numbers, Tight Tracking) */}
        <span className="text-metric text-2xl mb-1">
          £{columnLeads.reduce((sum, l) => sum + (SERVICE_CONVERSION_VALUES[l.service] ?? 1000), 0).toLocaleString()}
        </span>
        <div className="h-[1px] w-full bg-gradient-to-r from-white/10 to-transparent mt-3"></div>
      </div>

      {/* Droppable Column Area */}
      <div className="flex-1 overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none] outline-none" ref={setNodeRef}>
        <SortableContext items={sortedLeads.map(l => l.id)}>
          <AnimatePresence>
            {sortedLeads.map(lead => (
              <SortableLeadCard
                key={lead.id}
                id={lead.id}
                lead={lead}
                setDepositModal={setDepositModal}
                setSelectedLead={setSelectedLead}
                updateStatus={updateStatus}
                STAFF_LIST={STAFF_LIST}
                updateAssignedTo={updateAssignedTo}
                timeAgo={timeAgo}
                clinic={clinic}
                onAddToWaitlist={onAddToWaitlist}
                onOpenPTMode={onOpenPTMode}
              />
            ))}
          </AnimatePresence>
        </SortableContext>

        {/* Sophisticated SVG Empty State */}
        {columnLeads.length === 0 && (
          <div className="h-40 rounded-[24px] flex flex-col items-center justify-center opacity-40 mt-2 border border-dashed border-white/10 bg-white/[0.02] backdrop-blur-sm relative overflow-hidden group">
            <div className="absolute inset-0 bg-gradient-to-b from-white/[0.02] to-transparent pointer-events-none" />
            <div className="relative w-12 h-12 mb-4 rounded-full bg-white/[0.03] border border-white/10 flex items-center justify-center group-hover:scale-110 transition-transform duration-500">
               <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" className="text-white/40">
                  <path d="M12 2v4m0 12v4M4.93 4.93l2.83 2.83m8.48 8.48l2.83 2.83M2 12h4m12 0h4M4.93 19.07l2.83-2.83m8.48-8.48l2.83-2.83" />
                  <circle cx="12" cy="12" r="4" />
               </svg>
            </div>
            <span className="text-[10px] font-black text-white/40 uppercase tracking-[0.2em]">Ready for Leads</span>
          </div>
        )}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────

const KANBAN_COLUMNS = ["New Lead", "Booked", "Visited", "Treated"];
const BRANCHES = ["London HQ", "Manchester Clinic", "Birmingham Center", "Edinburgh Practice"];

function KanbanSkeleton() {
  return (
    <div className="flex min-w-max animate-pulse gap-6 overflow-hidden">
      {[1, 2, 3, 4].map(i => (
        <div key={i} className="flex-shrink-0 w-[280px] bg-white border border-black/5 rounded-[32px] p-5 flex flex-col h-[65vh]">
          <div className="flex items-center justify-between mb-6">
            <div className="h-4 w-24 bg-black/5 rounded-full"></div>
            <div className="h-5 w-8 bg-black/5 rounded-full"></div>
          </div>
          <div className="flex-1 space-y-4 overflow-hidden">
            {[1, 2, 3].map(j => (
              <div key={j} className="bg-black/[0.02] p-5 rounded-[24px] h-36 border border-black/5">
                <div className="h-4 w-3/4 bg-black/5 rounded-full mb-3"></div>
                <div className="h-3 w-1/2 bg-black/5 rounded-full mb-5"></div>
                <div className="flex gap-2">
                  <div className="h-8 w-20 bg-[#ffffff0d] rounded-full"></div>
                  <div className="h-8 w-12 bg-[#ffffff0d] rounded-full"></div>
                </div>
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

// ── Premium Toast Notification ───────────────────────────────────────────
function Toast({ message, type, onClose }: { message: string, type: 'success' | 'error', onClose: () => void }) {
  useEffect(() => {
    const timer = setTimeout(onClose, 5000);
    return () => clearTimeout(timer);
  }, [onClose]);

  return (
    <motion.div
      initial={{ y: 50, opacity: 0, scale: 0.9 }}
      animate={{ y: 0, opacity: 1, scale: 1 }}
      exit={{ y: 20, opacity: 0, scale: 0.9 }}
      className="fixed bottom-10 left-1/2 -translate-x-1/2 z-[200] flex items-center gap-3 px-6 py-4 bg-[#1A1A1A] border border-white/10 rounded-2xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] backdrop-blur-xl"
    >
      <div className={`p-2 rounded-xl ${type === 'success' ? 'bg-[#87A96B]/20 text-[#87A96B]' : 'bg-red-500/20 text-red-500'}`}>
        {type === 'success' ? <Check className="w-4 h-4" /> : <AlertTriangle className="w-4 h-4" />}
      </div>
      <p className="text-[13px] font-medium text-white/90 tracking-tight">{message}</p>
      <button onClick={onClose} className="ml-4 text-white/40 hover:text-white/70 transition-colors">
        <X className="w-4 h-4" />
      </button>
      <div className={`absolute bottom-0 left-0 h-0.5 ${type === 'success' ? 'bg-[#87A96B]' : 'bg-red-500'} animate-toast-progress`} style={{ width: '100%' }} />
    </motion.div>
  );
}

export default function AdminDashboard() {
  const navigate = useNavigate();
  const { session, profile, isAdmin, signOut, loading: authLoading } = useAuth();
  const [multiBranchMode, setMultiBranchMode] = useState(false);
  const [selectedBranch, setSelectedBranch] = useState(BRANCHES[0]);
  const [isBranchDropdownOpen, setIsBranchDropdownOpen] = useState(false);
  const [leads, setLeads] = useState<ConsultationRequest[]>([]);
  const [performedTreatments, setPerformedTreatments] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [isBroadcasting, setIsBroadcasting] = useState(false);
  const [toast, setToast] = useState<{ message: string, type: 'success' | 'error' } | null>(null);
  const [selectedLead, setSelectedLead] = useState<ConsultationRequest | null>(null);
  const [isRecording, setIsRecording] = useState(false);
  const [dictationText, setDictationText] = useState("");
  const [activeTab, setActiveTab] = useState<"action" | "pipeline" | "vault">("action");
  const [isExpertModeOpen, setIsExpertModeOpen] = useState(false);
  const [analyticsMonth, setAnalyticsMonth] = useState<number>(new Date().getMonth());
  const [analyticsYear, setAnalyticsYear] = useState<number>(new Date().getFullYear());
  const [searchTerm, setSearchTerm] = useState("");
  const debouncedSearchTerm = useDebounce(searchTerm, 300);
  const [limit, setLimit] = useState(50);
  const [hasMore, setHasMore] = useState(true);
  const [isFetchingMore, setIsFetchingMore] = useState(false);
  const [isInitialLoad, setIsInitialLoad] = useState(true);
  const [zeroMode, setZeroMode] = useState(false);
  const observerTarget = React.useRef(null);

  const [selectedDate, setSelectedDate] = useState<string>("");
  const [selectedThreadId, setSelectedThreadId] = useState<string | null>(null);
  const [omniMessages, setOmniMessages] = useState<OmniMessage[]>([]);

  // Treatment Logging State
  const [treatmentModal, setTreatmentModal] = useState<{ isOpen: boolean; leadId: string; leadName: string; initialService: string } | null>(null);
  const [treatmentForm, setTreatmentForm] = useState({
    treatmentName: "",
    amount: 0,
    notes: "",
    doctorId: ""
  });
  const [replyText, setReplyText] = useState("");
  const [depositModal, setDepositModal] = useState<{ isOpen: boolean; leadName: string; payUrl: string }>({ isOpen: false, leadName: "", payUrl: "" });
  const [aiBriefing, setAiBriefing] = useState<string | null>(null);
  const [draftDropoffs, setDraftDropoffs] = useState(0);
  const [clinic, setClinic] = useState<any>(null);
  const [treatments, setTreatments] = useState<any[]>([]);
  const [isSaving, setIsSaving] = useState(false);
  const [editingTreatment, setEditingTreatment] = useState<any | null>(null);
  const [isWaitlistOpen, setIsWaitlistOpen] = useState(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);

  // Toast Notification State

  useEffect(() => {
    if (toast) {
      const timer = setTimeout(() => setToast(null), 3000);
      return () => clearTimeout(timer);
    }
  }, [toast]);

  const showToast = (message: string, type: 'success' | 'error' = 'success') => {
    setToast({ message, type });
  };
  const [notifications, setNotifications] = useState<{ id: string; message: string; time: string; read: boolean }[]>([]);
  const [isNotificationOpen, setIsNotificationOpen] = useState(false);
  const [reviewPrompt, setReviewPrompt] = useState<{ isOpen: boolean; leadId: string; leadName: string } | null>(null);
  const [schedulingLead, setSchedulingLead] = useState<{ id: string; name: string; targetStatus: ConsultationRequest["status"] } | null>(null);
  const [appointmentDateInput, setAppointmentDateInput] = useState<{ date: string; time: string; doctorId: string; resourceId: string; duration: number }>({
    date: "",
    time: "",
    doctorId: "",
    resourceId: "",
    duration: 30
  });
  const [doctors, setDoctors] = useState<Profile[]>([]);
  const [resources, setResources] = useState<any[]>([]); // Chairs/Rooms
  const [invitations, setInvitations] = useState<Invitation[]>([]);
  const [teamMembers, setTeamMembers] = useState<Profile[]>([]);
  const [isInviteModalOpen, setIsInviteModalOpen] = useState(false);
  const [inviteEmail, setInviteEmail] = useState("");
  const [inviteRole, setInviteRole] = useState<"admin" | "staff">("staff");
  const [editingProfile, setEditingProfile] = useState<Profile | null>(null);
  const [isUpdatingProfile, setIsUpdatingProfile] = useState(false);

  // Marketing Sync State
  const [adConnections, setAdConnections] = useState<any[]>([]);
  const [adMetrics, setAdMetrics] = useState({ spend: 0, clicks: 0, impressions: 0 });
  const [isAutoTagMenuOpen, setIsAutoTagMenuOpen] = useState(false);
  const [selectedPlatform, setSelectedPlatform] = useState<'meta' | 'google' | null>(null);

  // Tablet PT Mode State
  const [isPTModeOpen, setIsPTModeOpen] = useState(false);
  const [ptModeData, setPtModeData] = useState<{
    patientName: string;
    treatmentName: string;
    totalPrice: number;
    beforeImage: string;
    afterImage: string;
  } | null>(null);

  // 🔴 LIVE Traffic State — powered by Supabase Realtime
  const [trafficStats, setTrafficStats] = useState({
    "Direct": 0, "Google": 0, "Social": 0, "Google (Organic)": 0, "Instagram": 0
  });

  // ── Sync Data Logic (Micro-interaction) ──────────────────────────────────
  const [syncState, setSyncState] = useState<'idle' | 'syncing' | 'success'>('idle');
  const handleSync = async () => {
    setSyncState('syncing');
    await fetchLeads();
    // Simulate complex background processing
    await new Promise(r => setTimeout(r, 1500));
    setSyncState('success');
    setTimeout(() => setSyncState('idle'), 3000);
  };

  // Today's Appointments Memo
  const todaysLeads = useMemo(() => {
    const today = new Date().toISOString().split('T')[0];
    return leads.filter(lead => {
      if (!lead.appointment_date) return false;
      return lead.appointment_date.startsWith(today) && (lead.status === "Booked");
    }).sort((a, b) => new Date(a.appointment_date!).getTime() - new Date(b.appointment_date!).getTime());
  }, [leads]);

  // Mock Notification Simulation (engagement tracking)
  useEffect(() => {
    if (session) {
      const timer = setTimeout(() => {
        setNotifications(prev => [
          {
            id: Date.now().toString(),
            message: "🔔 Lee Min-ho just opened their Dental Implants PT link!",
            time: "Just now",
            read: false
          },
          ...prev
        ]);
      }, 5000);
      return () => clearTimeout(timer);
    }
  }, [session]);

  useEffect(() => {
    const fetchDrafts = async () => {
      const fifteenMinsAgo = new Date(Date.now() - 15 * 60000).toISOString();
      const { count } = await supabase
        .from('appointments')
        .select('*', { count: 'exact', head: true })
        .eq('status', 'draft')
        .lt('created_at', fifteenMinsAgo);
      if (count !== null) setDraftDropoffs(count);
    };

    const fetchAdData = async () => {
      if (!profile?.clinic_id) return;

      // Fetch connections
      const { data: conns } = await supabase
        .from('clinic_ad_connections')
        .select('*')
        .eq('status', 'connected');
      if (conns) setAdConnections(conns);

      // Fetch aggregated metrics for this month
      const startOfMonth = new Date(analyticsYear, analyticsMonth, 1).toISOString().split('T')[0];
      const endOfMonth = new Date(analyticsYear, analyticsMonth + 1, 0).toISOString().split('T')[0];

      const { data: metrics } = await supabase
        .from('clinic_ad_metrics')
        .select('spend_gbp, clicks, impressions')
        .gte('date', startOfMonth)
        .lte('date', endOfMonth);

      if (metrics) {
        const aggregated = metrics.reduce((acc, row) => ({
          spend: acc.spend + Number(row.spend_gbp || 0),
          clicks: acc.clicks + Number(row.clicks || 0),
          impressions: acc.impressions + Number(row.impressions || 0)
        }), { spend: 0, clicks: 0, impressions: 0 });
        setAdMetrics(aggregated);
      }
    };

    if (session) {
      fetchDrafts();
      fetchAdData();
      const interval = setInterval(fetchDrafts, 60000); // Check every minute
      return () => clearInterval(interval);
    }
  }, [session, profile, analyticsMonth, analyticsYear]);

  // 🔴 REALTIME: Subscribe to traffic_logs table for live dashboard updates
  useEffect(() => {
    if (!profile?.clinic_id) return;

    // Initial fetch from traffic_logs (last 30 days)
    const fetchTrafficLogs = async () => {
      const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
      const { data } = await supabase
        .from("traffic_logs")
        .select("source")
        .eq("clinic_id", profile.clinic_id)
        .gte("created_at", thirtyDaysAgo);

      if (data) {
        const stats = { "Direct": 0, "Google": 0, "Social": 0, "Google (Organic)": 0, "Instagram": 0, "Facebook": 0, "Referral": 0 };
        data.forEach((row: any) => {
          const s = row.source;
          if (s in stats) stats[s as keyof typeof stats]++;
          else if (s === "Referral") stats["Social"]++; // Grouping for simple view if needed
        });
        setTrafficStats(stats);
      }
    };

    fetchTrafficLogs();

    // Realtime channel for traffic_logs
    const channel = supabase
      .channel("traffic_logs_realtime")
      .on(
        "postgres_changes",
        { event: "INSERT", schema: "public", table: "traffic_logs", filter: `clinic_id=eq.${profile.clinic_id}` },
        () => { fetchTrafficLogs(); } // Refetch on any new visit
      )
      .subscribe();

    return () => { supabase.removeChannel(channel); };
  }, [profile?.clinic_id]);

  // ── Dynamic Analytics Logic (Hooks at top!) ──
  const dynamicRevenueData = useMemo(() => {
    const data = [
      { name: 'Week 1', Implants: 0, Invisalign: 0, Veneers: 0 },
      { name: 'Week 2', Implants: 0, Invisalign: 0, Veneers: 0 },
      { name: 'Week 3', Implants: 0, Invisalign: 0, Veneers: 0 },
      { name: 'Week 4', Implants: 0, Invisalign: 0, Veneers: 0 },
    ];

    leads.forEach(lead => {
      if (!lead || lead.status !== "Sale Closed") return;

      const dateSource = lead.treated_at || lead.appointment_date || lead.created_at;
      if (!dateSource) return;

      const d = new Date(dateSource);
      if (isNaN(d.getTime())) return;
      if (d.getMonth() !== analyticsMonth || d.getFullYear() !== analyticsYear) return;

      const day = d.getDate();
      let weekIndex = 0;
      if (day > 21) weekIndex = 3;
      else if (day > 14) weekIndex = 2;
      else if (day > 7) weekIndex = 1;

      // Use actual amount if available, fallback to estimated
      const actualTreatments = performedTreatments?.filter(pt => pt?.lead_id === lead.id) || [];
      const value = actualTreatments.length > 0
        ? actualTreatments.reduce((sum, pt) => sum + (Number(pt?.amount) || 0), 0)
        : (SERVICE_CONVERSION_VALUES[lead.service] || 1000);

      const service = lead.service || "";
      if (service.includes("Implant")) data[weekIndex].Implants += value;
      else if (service.includes("Invisalign")) data[weekIndex].Invisalign += value;
      else if (service.includes("Veneer")) data[weekIndex].Veneers += value;
    });

    return data;
  }, [leads, analyticsMonth, analyticsYear]);

  const treatmentDistribution = useMemo(() => {
    const counts = { Implants: 0, Invisalign: 0, Veneers: 0 };

    // 1. Count from performedTreatments
    (performedTreatments || []).forEach(pt => {
      if (!pt?.created_at) return;
      const d = new Date(pt.created_at);
      if (isNaN(d.getTime())) return;
      if (d.getMonth() !== analyticsMonth || d.getFullYear() !== analyticsYear) return;

      const name = pt.treatment_name || "";
      if (name.includes("Implant")) counts.Implants++;
      else if (name.includes("Invisalign")) counts.Invisalign++;
      else if (name.includes("Veneer")) counts.Veneers++;
    });

    // 2. Count from leads without explicit logging (legacy or pending)
    leads.forEach(lead => {
      if (!lead || lead.status !== "Sale Closed") return;
      const hasRecord = (performedTreatments || []).some(pt => pt?.lead_id === lead.id);
      if (hasRecord) return;

      const dateSource = lead.treated_at || lead.appointment_date || lead.created_at;
      if (!dateSource) return;

      const d = new Date(dateSource);
      if (isNaN(d.getTime())) return;
      if (d.getMonth() !== analyticsMonth || d.getFullYear() !== analyticsYear) return;

      const service = lead.service || "";
      if (service.includes("Implant")) counts.Implants++;
      else if (service.includes("Invisalign")) counts.Invisalign++;
      else if (service.includes("Veneer")) counts.Veneers++;
    });

    const totalPaid = Object.values(counts).reduce((a, b) => a + b, 0);

    // Dynamic mapping from DB treatments
    return (treatments || []).map(t => {
      if (!t) return null;
      let count = 0;
      const serviceName = t.service_name || "";
      if (serviceName.includes("Implant")) count = counts.Implants;
      else if (serviceName.includes("Invisalign")) count = counts.Invisalign;
      else if (serviceName.includes("Veneer")) count = counts.Veneers;
      else {
        // Fallback for other treatments
        count = (performedTreatments || []).filter(pt => pt?.treatment_name === serviceName).length;
      }

      return {
        name: serviceName,
        value: totalPaid > 0 ? (count / totalPaid) * 100 : 0,
        color: t.color || "#3b82f6",
        count: count
      };
    }).filter((item): item is NonNullable<typeof item> => item !== null)
      .sort((a, b) => b.count - a.count);
  }, [leads, performedTreatments, analyticsMonth, analyticsYear]);

  // High-End Revenue Engine KPIs (Powered by Supabase RPC)
  const [revenueMetrics, setRevenueMetrics] = useState({
    systemGeneratedRevenue: 0,
    marketingROAS: 0,
    revenueAtRisk: 0
  });

  useEffect(() => {
    async function fetchMetrics() {
      if (!profile?.clinic_id) return;

      const { data, error } = await supabase.rpc('get_revenue_metrics', {
        p_clinic_id: profile.clinic_id
      });

      if (!error && data) {
        setRevenueMetrics({
          systemGeneratedRevenue: Number(data.system_generated_revenue || 0),
          marketingROAS: Number(data.marketing_roas || 0),
          revenueAtRisk: Number(data.revenue_at_risk || 0)
        });
      }
    }
    fetchMetrics();
  }, [leads, profile?.clinic_id]); // Re-fetch when 'leads' array updates via realtime

  const { systemGeneratedRevenue, marketingROAS, revenueAtRisk } = revenueMetrics;

  const topSource = useMemo(() => {
    const directCount = leads.filter(l => !l.utm_source && !l.referrer).length;
    const googleCount = leads.filter(l => l.utm_source === "google" || l.utm_source?.includes("search")).length;
    const instagramCount = leads.filter(l => l.utm_source === "instagram").length;
    const socialCount = leads.filter(l => (l.referrer || l.utm_source) && l.utm_source !== "google" && l.utm_source !== "instagram").length;

    const segments = [
      { label: "Direct Traffic", count: directCount },
      { label: "Google / Search", count: googleCount },
      { label: "Instagram", count: instagramCount },
      { label: "Referrer / Social", count: socialCount },
    ];

    return segments.reduce((prev, current) => (prev.count >= current.count ? prev : current), segments[0]);
  }, [leads]);

  useEffect(() => {
    if (leads.length > 0 && !aiBriefing) {
      generateDailyBriefing(leads).then(setAiBriefing);
    }
  }, [leads, aiBriefing]);

  const pointerSensor = useSensor(PointerSensor, { activationConstraint: { distance: 5 } });
  const keyboardSensor = useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates });
  const sensors = useSensors(pointerSensor, keyboardSensor);

  // ── Omnichannel Inbox Data Flow ──────────────────────────────────
  useEffect(() => {
    if (!profile?.clinic_id) return;

    const fetchMessages = async () => {
      const { data } = await supabase
        .from('messages')
        .select('*')
        .eq('clinic_id', profile.clinic_id)
        .order('created_at', { ascending: true });
      if (data) setOmniMessages(data as OmniMessage[]);
    };

    fetchMessages();

    const channel = supabase
      .channel('omnichannel_messages_live')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'messages', filter: `clinic_id=eq.${profile.clinic_id}` },
        (payload) => {
          if (payload.eventType === 'INSERT') {
            setOmniMessages(prev => [...prev, payload.new as OmniMessage]);
          } else if (payload.eventType === 'UPDATE') {
            setOmniMessages(prev => prev.map(m => m.id === payload.new.id ? (payload.new as OmniMessage) : m));
          }
        }
      )
      .subscribe();

    return () => { supabase.removeChannel(channel); };
  }, [profile?.clinic_id]);

  const omniThreads = useMemo(() => {
    const threadMap = new Map<string, OmniThread>();

    // For testing and onboarding, inject a mock thread if empty
    const displayMessages = omniMessages.length === 0 ? [
      {
        id: "mock1", lead_id: "mock-vip", sender_raw: "+447700900077", channel: "whatsapp", content: "Hi! I am looking for full arch implants. Do you offer financing?", direction: "inbound", is_read: false, created_at: new Date(Date.now() - 600000).toISOString()
      } as OmniMessage,
      {
        id: "mock2", lead_id: "mock-ig", sender_raw: "@ji_soo_k", channel: "instagram", content: "Love the recent veneer case! How much does an upper 8 cost?", direction: "inbound", is_read: true, created_at: new Date(Date.now() - 3600000).toISOString()
      } as OmniMessage,
      {
        id: "mock3", lead_id: "mock-sms", sender_raw: "+447911123456", channel: "sms", content: "I'll be 5 mins late to my appointment.", direction: "inbound", is_read: true, created_at: new Date(Date.now() - 7200000).toISOString()
      } as OmniMessage
    ] : omniMessages;

    displayMessages.forEach(msg => {
      const threadId = msg.sender_raw;
      const existing = threadMap.get(threadId);

      if (!existing) {
        const lead = leads.find(l => l.id === msg.lead_id);
        const recipientName = lead ? lead.name : msg.sender_raw;
        let sourceLabel = 'Website';
        let avatarStr = recipientName.substring(0, 2).toUpperCase();

        if (msg.channel === 'whatsapp') sourceLabel = 'WhatsApp';
        if (msg.channel === 'sms') sourceLabel = 'SMS';
        if (msg.channel === 'instagram') sourceLabel = 'Instagram';

        // Override avatars for mocks
        if (msg.sender_raw === "@ji_soo_k") avatarStr = "JS";
        if (msg.sender_raw === "+447700900077") avatarStr = "VIP";

        threadMap.set(threadId, {
          id: threadId,
          recipient: recipientName,
          source: sourceLabel,
          channel: msg.channel,
          avatar: avatarStr,
          lastMsg: msg.content,
          time: timeAgo(msg.created_at),
          unread: (!msg.is_read && msg.direction === 'inbound'),
          messages: [msg]
        });
      } else {
        existing.messages.push(msg);
        existing.lastMsg = msg.content;
        existing.time = timeAgo(msg.created_at);
        if (!msg.is_read && msg.direction === 'inbound') {
          existing.unread = true;
        }
      }
    });

    return Array.from(threadMap.values()).sort((a, b) => {
      const lastA = a.messages[a.messages.length - 1];
      const lastB = b.messages[b.messages.length - 1];
      return new Date(lastB.created_at).getTime() - new Date(lastA.created_at).getTime();
    });
  }, [omniMessages, leads]);

  const handleSendMessage = async () => {
    if (!replyText.trim() || !selectedThreadId || !profile?.clinic_id) return;
    const thread = omniThreads.find(t => t.id === selectedThreadId);
    if (!thread) return;

    const tempMsg: OmniMessage = {
      id: Math.random().toString(),
      clinic_id: profile.clinic_id,
      lead_id: thread.messages[0].lead_id,
      sender_raw: thread.id,
      channel: thread.channel as any,
      content: replyText,
      direction: 'outbound',
      is_read: true,
      created_at: new Date().toISOString()
    };

    setReplyText("");

    // Optimistic update
    if (!thread.id.startsWith("mock")) {
      setOmniMessages(prev => [...prev, tempMsg]);
      await supabase.from('messages').insert({
        clinic_id: tempMsg.clinic_id,
        lead_id: tempMsg.lead_id,
        sender_raw: tempMsg.sender_raw,
        channel: tempMsg.channel,
        content: tempMsg.content,
        direction: tempMsg.direction,
        is_read: true
      });
    }
  };

  const handleAddToWaitlist = async (leadId: string) => {
    const { error } = await supabase
      .from('consultation_requests')
      .update({ waitlist_status: 'active' as any })
      .eq('id', leadId);

    if (error) {
      console.error('Error adding to waitlist:', error);
      setToast({ message: "Failed to add to waitlist.", type: 'error' });
    } else {
      setToast({ message: "Lead added to Priority Waitlist.", type: 'success' });
    }
  };

  const broadcastAvailability = async () => {
    setIsBroadcasting(true);
    try {
      // 1. Create a dummy cancelled slot for demo purposes if none exist
      // In production, this would be triggered by an ACTUAL cancellation event
      const { data: slot, error: slotError } = await supabase
        .from('cancelled_slots')
        .insert([{
          clinic_id: profile?.clinic_id,
          service_name: 'Dental Implants',
          start_time: new Date(Date.now() + 24 * 3600000).toISOString(), // Tomorrow
        }])
        .select()
        .single();

      if (slotError) throw slotError;

      // 2. Trigger Edge Function to notify matching waitlist leads
      const { data, error } = await supabase.functions.invoke('broadcast-slot', {
        body: { slot_id: slot.id }
      });

      if (error) throw error;
      setToast({ message: `Broadcast sent to ${data.count} matching patients!`, type: 'success' });
    } catch (err: any) {
      console.error('Broadcast failed:', err);
      setToast({ message: "Broadcast failed. Check logs.", type: 'error' });
    } finally {
      setIsBroadcasting(false);
    }
  };

  const [marketingROI, setMarketingROI] = useState<any[]>([]);

  const fetchMarketingROI = async () => {
    const { data, error } = await supabase
      .from('marketing_roi')
      .select('*');

    if (error) {
      console.error('Error fetching Marketing ROI:', error);
      return;
    }
    setMarketingROI(data || []);
  };

  useEffect(() => {
    if (profile?.clinic_id) {
      loadDashboardData();
      fetchMarketingROI();

      const channel = supabase
        .channel('marketing-roi-changes')
        .on('postgres_changes', { event: '*', schema: 'public', table: 'clinic_ad_metrics' }, () => {
          fetchMarketingROI();
        })
        .subscribe();

      return () => {
        supabase.removeChannel(channel);
      };
    }
  }, [profile?.clinic_id]);

  const loadDashboardData = async () => {
    if (!profile?.clinic_id) return;
    setLoading(true);

    const cacheKey = `static_data_${profile.clinic_id}`;
    const cachedData = sessionStorage.getItem(cacheKey);

    if (cachedData) {
      const parsed = JSON.parse(cachedData);
      setClinic(parsed.clinic);
      setTreatments(parsed.treatments);
      setDoctors(parsed.teamData);
      setResources(parsed.resources);
      setTeamMembers(parsed.teamData);
    } else {
      // Fetch Clinic Data
      const { data: clinicData } = await supabase.from('clinics').select('*').eq('id', profile.clinic_id).single();
      const { data: treatmentsData } = clinicData ? await supabase.from('clinic_treatments').select('*').eq('clinic_id', clinicData.id) : { data: null };
      const { data: resourcesData } = clinicData ? await supabase.from('resources').select('*').eq('clinic_id', clinicData.id) : { data: null };
      const { data: teamData } = clinicData ? await supabase.from('profiles').select('*').eq('clinic_id', clinicData.id) : { data: null };

      if (clinicData) setClinic(clinicData);
      if (treatmentsData) setTreatments(treatmentsData);
      if (resourcesData) setResources(resourcesData);
      if (teamData) {
        setTeamMembers(teamData);
        setDoctors(teamData);
      }

      sessionStorage.setItem(cacheKey, JSON.stringify({
        clinic: clinicData || null,
        treatments: treatmentsData || [],
        resources: resourcesData || [],
        teamData: teamData || []
      }));
    }

    // Always fetch dynamic data (invitations)
    const { data: inviteData } = await supabase
      .from('invitations')
      .select('*')
      .eq('clinic_id', profile.clinic_id)
      .eq('status', 'pending');
    if (inviteData) setInvitations(inviteData);

    await fetchLeads();

    // Fetch Performed Treatments
    const { data: perfData } = await supabase
      .from('performed_treatments')
      .select('*')
      .eq('clinic_id', profile.clinic_id);
    if (perfData) setPerformedTreatments(perfData);

    setLoading(false);
  };

  // ── Staff ROI Analytics Calculation ──────────────────────────────────────
  const dynamicStaffList = useMemo(() => {
    const fromTeam = teamMembers.map(m => m.full_name).filter((n): n is string => !!n);
    const fromLeads = Array.from(new Set(leads.map(l => l.assigned_to).filter((n): n is string => !!n)));
    return Array.from(new Set([...fromTeam, ...fromLeads]));
  }, [teamMembers, leads]);

  const staffROI = useMemo(() => {
    return dynamicStaffList.map(staff => {
      const staffLeads = leads.filter(l => l.assigned_to === staff);
      const totalLeads = staffLeads.length;
      const convertedLeads = staffLeads.filter(l => l.status === "Sale Closed").length;
      const totalRevenue = staffLeads
        .filter(l => l.status === "Sale Closed")
        .reduce((sum, l) => sum + (SERVICE_CONVERSION_VALUES[l.service] || 1000), 0);

      const conversionRate = totalLeads > 0 ? (convertedLeads / totalLeads) * 100 : 0;

      return {
        name: staff,
        conversion: Math.round(conversionRate),
        revenue: totalRevenue,
        leads: totalLeads
      };
    }).sort((a, b) => b.revenue - a.revenue);
  }, [dynamicStaffList, leads]);

  const fetchLeads = async (currentLimit = limit, append = false) => {
    if (!profile?.clinic_id) return;
    if (append) setIsFetchingMore(true);

    const { data, count, error } = await supabase
      .from('consultation_requests')
      .select('*', { count: 'exact' })
      .eq('clinic_id', profile.clinic_id)
      .order('created_at', { ascending: false })
      .limit(currentLimit);

    if (error) {
      console.error("Error fetching leads:", error);
    } else {
      setLeads(data || []);
      if (!append && data) {
        try {
          localStorage.setItem(`leads_cache_${profile.clinic_id}`, JSON.stringify(data.slice(0, 50)));
        } catch (e) { }
      }
      if (count !== null && data && data.length >= count) {
        setHasMore(false);
      } else {
        setHasMore(true);
      }
    }

    if (append) setIsFetchingMore(false);
    if (isInitialLoad) setIsInitialLoad(false); // Added this line
  };

  // --- OFFLINE-PROOF SYNC (Local Caching & Realtime WebSockets) ---
  useEffect(() => {
    if (!profile?.clinic_id) return;

    // 1. Instant Initial Load from Cache
    const cachedLeadsStr = localStorage.getItem(`leads_cache_${profile.clinic_id}`);
    if (cachedLeadsStr && leads.length === 0) {
      try {
        setLeads(JSON.parse(cachedLeadsStr));
      } catch (e) {
        console.error("Failed to parse cached leads");
      }
    }

    // 2. Realtime WebSocket Subscription
    const channel = supabase.channel(`public:consultation_requests:${profile.clinic_id}`)
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'consultation_requests',
          filter: `clinic_id=eq.${profile.clinic_id}`
        },
        (payload) => {
          if (payload.eventType === 'INSERT') {
            setLeads(prev => {
              if (prev.some(l => l.id === payload.new.id)) return prev; // Prevent duplicate if added optimistically
              const newLeads = [payload.new as ConsultationRequest, ...prev];
              localStorage.setItem(`leads_cache_${profile.clinic_id}`, JSON.stringify(newLeads.slice(0, 50)));
              return newLeads;
            });
          } else if (payload.eventType === 'UPDATE') {
            setLeads(prev => {
              const updated = prev.map(l => l.id === payload.new.id ? { ...l, ...payload.new } : l);
              localStorage.setItem(`leads_cache_${profile.clinic_id}`, JSON.stringify(updated.slice(0, 50)));
              return updated;
            });
          } else if (payload.eventType === 'DELETE') {
            setLeads(prev => {
              const filtered = prev.filter(l => l.id !== payload.old.id);
              localStorage.setItem(`leads_cache_${profile.clinic_id}`, JSON.stringify(filtered.slice(0, 50)));
              return filtered;
            });
          }
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [profile?.clinic_id]);

  useEffect(() => {
    const observer = new IntersectionObserver(
      entries => {
        if (entries[0].isIntersecting && hasMore && !isFetchingMore) {
          setLimit(prev => {
            const next = prev + 50;
            fetchLeads(next, true);
            return next;
          });
        }
      },
      { threshold: 0.1 }
    );

    if (observerTarget.current) {
      observer.observe(observerTarget.current);
    }

    return () => {
      if (observerTarget.current) {
        observer.unobserve(observerTarget.current);
      }
    };
  }, [hasMore, isFetchingMore]);

  const handleInviteStaff = async (email: string, role: "admin" | "staff") => {
    if (!email) {
      alert("Please enter a valid email address.");
      return;
    }

    try {
      const token = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);

      let data: any = null;

      // Handle demo mode bypass
      const isDemo = profile?.id === 'demo-user';
      if (isDemo) {
        data = {
          id: crypto.randomUUID(),
          clinic_id: profile?.clinic_id,
          email,
          role,
          token,
          status: 'pending',
          expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
          created_at: new Date().toISOString()
        };
        console.log("Demo mode: Mocked invitation created.", data);
      } else {
        const { data: dbData, error } = await supabase
          .from('invitations')
          .insert([{
            clinic_id: profile?.clinic_id,
            email,
            role,
            token,
            status: 'pending',
            expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString() // 7 days
          }])
          .select()
          .single();

        if (error) throw error;
        data = dbData;
      }

      if (data) {
        setInvitations(prev => [...prev, data]);
        setIsInviteModalOpen(false);
        setInviteEmail("");
        setInviteRole("staff");

        // Trigger the edge function to actually send the email via Resend
        if (!isDemo) {
          try {
            const { data: funcData, error: funcError } = await supabase.functions.invoke('send-staff-invite', {
              body: {
                email: email,
                role: role,
                token: token,
                clinic_name: clinic?.name || "London Smile Dental",
                origin: window.location.origin,
                invited_by: profile?.id
              }
            });

            if (funcError) throw funcError;

            // Check manual success flag from our custom 200 OK wrapper
            if (funcData && funcData.success === false) {
              throw new Error(funcData.error || "Unknown email delivery error");
            }

            alert("Invitation created and emailed successfully!");
          } catch (err: any) {
            console.error("Failed to trigger invite email:", err);
            alert(`Invitation created in database, but email failed:\n\n${err.message || String(err)}`);
          }
        } else {
          // In demo mode, show the generated link so the user can test the flow
          const inviteurl = `${window.location.origin}/login?invite=${token}`;
          prompt(`[Demo Mode] Email sending is simulated. Copy this link to test the invitation acceptance flow manually:`, inviteurl);
        }
      }
    } catch (err: any) {
      console.error("Invite error:", err);
      alert(`Failed to create invitation: ${err.message}`);
    }
  };

  useEffect(() => {
    if (session) loadDashboardData();
  }, [session]);

  const createAuditLog = async (params: {
    leadId: string;
    leadName: string;
    actionType: 'STATUS_CHANGE' | 'DATE_UPDATE' | 'DELETED' | 'SLA_BREACH' | 'DEPOSIT_UPDATE';
    previousValue?: string;
    newValue?: string;
  }) => {
    try {
      if (!profile?.id || !profile?.clinic_id) return;

      await supabase
        .from('audit_logs')
        .insert([{
          clinic_id: profile.clinic_id,
          lead_id: params.leadId,
          user_id: profile.id,
          user_name: profile.full_name || 'System',
          lead_name: params.leadName,
          action_type: params.actionType,
          previous_value: params.previousValue,
          new_value: params.newValue
        }]);
    } catch (err) {
      console.error("Failed to write audit log:", err);
      // Silent fail as per Postel's Law
    }
  };

  const handleBroadcast = async () => {
    const waitlistedLeads = leads.filter(l => (l.status as any) === "Waitlisted");

    if (waitlistedLeads.length === 0) {
      setToast({ message: "Waitlist is currently empty", type: "error" });
      return;
    }

    setIsBroadcasting(true);
    try {
      const { data, error } = await supabase.functions.invoke('broadcast-waitlist', {
        body: {
          clinic_id: profile?.clinic_id,
          leads: waitlistedLeads.map(l => ({ id: l.id, name: l.name, phone: l.phone, email: l.email }))
        }
      });

      if (error) throw error;

      setToast({
        message: `Success: ${waitlistedLeads.length} Patients Notified`,
        type: "success"
      });
    } catch (err: any) {
      console.error("[BROADCAST ERROR]", err);
      setToast({ message: "Broadcast Failed. Please try again.", type: "error" });
    } finally {
      setIsBroadcasting(false);
    }
  };

  const updateStatus = async (id: string, newStatus: ConsultationRequest["status"]) => {
    // Validation
    if (!KANBAN_COLUMNS.includes(newStatus)) {
      console.error("Attempted to update to invalid status:", newStatus);
      return;
    }

    const lead = leads.find(l => l.id === id);
    const updateData: any = {
      status: newStatus
    };

    // Auto-schedule recall for completed/archived leads
    if (newStatus === 'Closed Won' || newStatus === 'Archived' || newStatus === 'Abandoned') {
      updateData.recall_interval_months = 6;
    }

    // Track treatment start
    if (newStatus === "Closed Won") {
      updateData.treated_at = new Date().toISOString();
    }

    // Track first contact time
    if ((lead?.status === "New Lead") && newStatus !== "New Lead" && !lead?.first_contact_at) {
      updateData.first_contact_at = new Date().toISOString();
    }

    const { error } = await supabase
      .from("consultation_requests")
      .update(updateData)
      .eq("id", id);

    if (error) {
      console.error("Error updating status:", error);
      alert(`Update failed: ${error.message}. The board will refresh.`);
      fetchLeads(); // Rollback optimistic update
      return;
    }

    // --- REPUTATION AUTOPILOT TRIGGER ---
    if (newStatus === "Treated" && lead && lead.phone) {
      supabase.functions.invoke('reputation-autopilot', {
        body: {
          lead_id: id,
          lead_name: lead.name,
          lead_phone: lead.phone,
          clinic_name: clinic?.name || "Hanlan OC"
        }
      }).catch(e => console.error("Reputation Autopilot Error:", e));
    }

    // Record Audit Log (Postel's Law - Non-blocking)
    if (lead && lead.status !== newStatus) {
      createAuditLog({
        leadId: id,
        leadName: lead.name,
        actionType: 'STATUS_CHANGE',
        previousValue: lead.status,
        newValue: newStatus
      });
    }

    // Auto-trigger review SMS when status → "Visited"
    if (newStatus === "Consultation Done" && lead && !lead.review_requested_at && lead.email) {
      supabase.functions.invoke('send_review_sms', {
        body: {
          lead_id: id,
          name: lead.name,
          email: lead.email,
          phone: lead.phone,
          service: lead.service
        }
      }).catch(e => console.error("Review request error:", e));

      // Update DB to mark as requested
      supabase
        .from("consultation_requests")
        .update({ review_requested_at: new Date().toISOString() })
        .eq('id', id);
    }

    fetchLeads();
  };

  const handleRevokeInvite = async (inviteId: string) => {
    if (!confirm("Are you sure you want to cancel this invitation?")) return;

    // Optimistic Update
    setInvitations(prev => prev.filter(inv => inv.id !== inviteId));

    const { error } = await supabase
      .from('invitations')
      .delete()
      .eq('id', inviteId);

    if (error) {
      console.error("Error revoking invite:", error);
      alert(`Failed to revoke invitation: ${error.message}`);
      // Refresh to restore state on error
      const { data } = await supabase.from('invitations').select('*').eq('clinic_id', profile?.clinic_id).eq('status', 'pending');
      if (data) setInvitations(data);
    }
  };

  const handleMoveToWaitlistStatus = async (leadId: string) => {
    // Optimistic UI Update
    setLeads(prev => prev.map(l => l.id === leadId ? { ...l, status: "Waitlisted" as any } : l));
    setIsWaitlistOpen(true); // Auto-open panel to show result

    const { error } = await supabase
      .from("consultation_requests")
      .update({ status: "Waitlisted" })
      .eq("id", leadId);

    if (error) {
      console.error("Error moving to waitlist:", error);
      alert(`Update failed: ${error.message}.`);
      fetchLeads(); // Rollback
      return;
    }

    // Refresh to ensure integrity
    fetchLeads();
  };


  const handleDragEnd = async (event: DragEndEvent) => {
    const { active, over } = event;
    if (!over) return;

    const leadId = active.id as string;
    let newStatus = over.id as string;

    // If dropped over another lead card, find that lead's status
    if (!KANBAN_COLUMNS.includes(newStatus)) {
      const overLead = leads.find(l => l.id === newStatus);
      if (overLead) {
        newStatus = overLead.status;
      } else {
        // Validation: If it's still not a column name, it's invalid
        console.warn("Invalid drop target:", newStatus);
        return;
      }
    }

    // Safety: Ensure newStatus is a valid column name and NOT a UUID
    if (!KANBAN_COLUMNS.includes(newStatus)) {
      console.error("Critical: newStatus is not a valid column:", newStatus);
      return;
    }

    const lead = leads.find(l => l.id === leadId);
    if (lead && lead.status !== newStatus) {

      // --- ZERO-TRAINING KANBAN GUARD ---
      // Guard: Prevent drop to 'Booked' without Date
      if (newStatus === "Booked" && !lead.appointment_date) {
        setToast({
          message: "❌ Training Guard: Appointment date is required for 'Booked' status. Reverting card.",
          type: "error"
        });
        return; // dnd-kit auto-reverts
      }

      // Prevent drop to 'Treated' without a recorded amount or confirmed visited status
      if (newStatus === "Treated" && lead.status !== "Visited") {
        // Warning but allow if confirmed? No, let's keep it strict for the engine.
        // For now, let's just implement the requested Booked guard.
      }

      // Trigger Review Prompt if moving to Treatment Started (handled AFTER date selection if needed)

      // Trigger Appointment Date Modal if moving to Booked and modal logic exists
      if (newStatus === "Booked" && !lead.appointment_date) {
        setSchedulingLead({ id: leadId, name: lead.name, targetStatus: newStatus as ConsultationRequest["status"] });

        // Use existing date if available, otherwise tomorrow
        const baseDate = new Date();
        baseDate.setDate(baseDate.getDate() + 1);

        setAppointmentDateInput({
          date: baseDate.toISOString().split('T')[0],
          time: "10:00",
          doctorId: lead.doctor_id || "",
          resourceId: lead.resource_id || "",
          duration: lead.duration_minutes || 30
        });
        return;
      }

      // Trigger Treatment Log Modal if moving to Treated
      if (newStatus === "Sale Closed") {
        setTreatmentModal({
          isOpen: true,
          leadId: leadId,
          leadName: lead.name,
          initialService: lead.service
        });
        setTreatmentForm({
          treatmentName: lead.service,
          amount: SERVICE_CONVERSION_VALUES[lead.service] || 1000,
          notes: "",
          doctorId: lead.doctor_id || ""
        });
        return;
      }
      trackEvent('lead_conversion_started', { leadId, service: lead.service });
      return;
    }

    // Optimistic UI Update
    setLeads(prev => prev.map(l => l.id === leadId ? { ...l, status: newStatus as ConsultationRequest["status"] } : l));
    await updateStatus(leadId, newStatus as ConsultationRequest["status"]);
  };

  const handleConfirmAppointment = async () => {
    if (!schedulingLead || !appointmentDateInput.date || !appointmentDateInput.time || !appointmentDateInput.doctorId || !appointmentDateInput.resourceId) return;

    const startTime = new Date(`${appointmentDateInput.date}T${appointmentDateInput.time}`);
    const appointmentISO = startTime.toISOString();
    const endTime = new Date(startTime.getTime() + appointmentDateInput.duration * 60000);
    const endTimeISO = endTime.toISOString();

    setLoading(true);

    try {
      // 1. Double-booking Validation (Conflict Detection)
      // Check for overlapping appointments for the SAME DOCTOR or SAME RESOURCE
      const { data: conflicts, error: conflictError } = await supabase
        .from('appointments')
        .select('id, scheduled_at, duration_minutes, doctor_id, resource_id')
        .or(`doctor_id.eq.${appointmentDateInput.doctorId},resource_id.eq.${appointmentDateInput.resourceId}`)
        .filter('status', 'in', '("pending","confirmed")');

      if (conflictError) throw conflictError;

      const hasConflict = conflicts?.some(apt => {
        const aptStart = new Date(apt.scheduled_at);
        const aptEnd = new Date(aptStart.getTime() + apt.duration_minutes * 60000);

        // Overlap logic: (StartA < EndB) and (EndA > StartB)
        return (startTime < aptEnd) && (endTime > aptStart);
      });

      if (hasConflict) {
        alert("⚠️ DOUBLE-BOOKING DETECTED: Either the Doctor or the Chair is already booked for this time slot. Please select a different time or resource.");
        setLoading(false);
        return;
      }

      const targetStatus = schedulingLead.targetStatus;
      const updateData: any = {
        status: targetStatus,
        appointment_date: appointmentISO,
        doctor_id: appointmentDateInput.doctorId,
        resource_id: appointmentDateInput.resourceId,
        duration_minutes: appointmentDateInput.duration
      };

      if (targetStatus === "Sale Closed") {
        updateData.treated_at = appointmentISO;
      }

      // 2. Update Consultation Request
      const { error: leadError } = await supabase
        .from("consultation_requests")
        .update(updateData)
        .eq("id", schedulingLead.id);

      if (leadError) throw leadError;

      // 3. Create/Update Appointment Record
      const { error: aptError } = await supabase
        .from("appointments")
        .insert([{
          clinic_id: profile?.clinic_id,
          consultation_request_id: schedulingLead.id,
          doctor_id: appointmentDateInput.doctorId,
          resource_id: appointmentDateInput.resourceId,
          scheduled_at: appointmentISO,
          duration_minutes: appointmentDateInput.duration,
          status: "confirmed"
        }]);

      if (aptError) throw aptError;

      // Success
      if (targetStatus === "Sale Closed") {
        setReviewPrompt({ isOpen: true, leadId: schedulingLead.id, leadName: schedulingLead.name });
      }

      // Record Audit Log (Postel's Law - Non-blocking)
      const lead = leads.find(l => l.id === schedulingLead.id);
      createAuditLog({
        leadId: schedulingLead.id,
        leadName: schedulingLead.name,
        actionType: 'DATE_UPDATE',
        previousValue: lead?.appointment_date || 'None',
        newValue: appointmentISO
      });

      if (lead && lead.status !== targetStatus) {
        createAuditLog({
          leadId: schedulingLead.id,
          leadName: schedulingLead.name,
          actionType: 'STATUS_CHANGE',
          previousValue: lead.status,
          newValue: targetStatus
        });
      }

      setSchedulingLead(null);
      fetchLeads();
    } catch (err: any) {
      console.error("Booking failed:", err);
      alert(`Booking failed: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };



  const handleSaveTreatment = async () => {
    if (!treatmentModal || !treatmentForm.treatmentName || !treatmentForm.amount || !treatmentForm.doctorId) {
      alert("Please fill in all required fields.");
      return;
    }

    setLoading(true);
    try {
      // 1. Insert into performed_treatments
      const { error: perfError } = await supabase
        .from('performed_treatments')
        .insert([{
          clinic_id: profile?.clinic_id,
          lead_id: treatmentModal.leadId,
          doctor_id: treatmentForm.doctorId,
          treatment_name: treatmentForm.treatmentName,
          amount: treatmentForm.amount,
          notes: treatmentForm.notes
        }]);

      if (perfError) throw perfError;

      // 2. Update lead status to Treated
      const { error: leadError } = await supabase
        .from('consultation_requests')
        .update({
          status: 'Treated',
          treated_at: new Date().toISOString()
        })
        .eq('id', treatmentModal.leadId);

      if (leadError) throw leadError;

      // Success
      setReviewPrompt({ isOpen: true, leadId: treatmentModal.leadId, leadName: treatmentModal.leadName });

      // Record Audit Log
      createAuditLog({
        leadId: treatmentModal.leadId,
        leadName: treatmentModal.leadName,
        actionType: 'STATUS_CHANGE',
        previousValue: 'Visited',
        newValue: 'Treated'
      });

      setTreatmentModal(null);
      fetchLeads();
    } catch (err: any) {
      console.error("Logging treatment failed:", err);
      alert(`Logging treatment failed: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleMicClick = () => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      alert("Voice dictation is not supported in this browser. Please use Chrome.");
      return;
    }

    const recognition = new SpeechRecognition();
    recognition.lang = 'en-US';
    recognition.interimResults = false;
    recognition.maxAlternatives = 1;

    recognition.onstart = () => {
      setIsRecording(true);
    };

    recognition.onresult = (event: any) => {
      const transcript = event.results[0][0].transcript;
      setDictationText(prev => prev ? prev + " " + transcript : transcript);
    };

    recognition.onerror = (event: any) => {
      console.error("Speech recognition error", event.error);
      setIsRecording(false);
    };

    recognition.onend = () => {
      setIsRecording(false);
    };

    recognition.start();
  };

  const saveNotes = async () => {
    if (!selectedLead) return;
    const newNotes = dictationText;

    // Optimistic UI Update
    setLeads(prev => prev.map(l => l.id === selectedLead.id ? { ...l, notes: newNotes } : l));
    setSelectedLead({ ...selectedLead, notes: newNotes });
    setDictationText("");

    const { error } = await supabase.from("consultation_requests").update({ notes: newNotes }).eq('id', selectedLead.id);
    if (error) {
      alert("Error saving notes: " + error.message);
      fetchLeads(); // Rollback
    }
  };

  // Sync dictationText when selectedLead changes
  useEffect(() => {
    if (selectedLead) {
      setDictationText(selectedLead.notes || "");
    }
  }, [selectedLead]);

  const updateAssignedTo = async (id: string, staffName: string) => {
    await supabase
      .from("consultation_requests")
      .update({ assigned_to: staffName || null })
      .eq("id", id);
    fetchLeads();
  };

  const handleLogout = async () => {
    await signOut();
    navigate("/login");
  };

  // Session handling removed as it's now managed by ProtectedRoute and AuthContext


  // ── Stats ──
  const now = new Date();
  const currentMonth = now.getMonth();
  const currentYear = now.getFullYear();

  const thisMonthLeads = leads.filter(l => {
    const d = new Date(l.created_at);
    return d.getMonth() === currentMonth && d.getFullYear() === currentYear;
  });

  const totalLeads = leads.length;
  const thisMonthNew = thisMonthLeads.length;

  const newLeads = leads.filter(l => l.status === "New Lead").length;
  const newLeadsValue = leads.filter(l => l.status === "New Lead").reduce((sum, l) => sum + (SERVICE_CONVERSION_VALUES[l.service] ?? 1000), 0);
  const ghostPatients = leads.filter(l => l.status === "Abandoned").length;
  const ghostLoss = leads.filter(l => l.status === "Abandoned").reduce((sum, l) => sum + (SERVICE_CONVERSION_VALUES[l.service] ?? 1000), 0);
  const confirmedLeads = totalLeads - ghostPatients;

  const allTimeRevenue = leads.filter(l => l.status === "Sale Closed").reduce((sum, l) => sum + (SERVICE_CONVERSION_VALUES[l.service] ?? 1000), 0);
  const monthlySecuredRevenue = dynamicRevenueData.reduce((sum, w) => sum + w.Implants + w.Invisalign + w.Veneers, 0);

  const monthlyPipelineRemaining = thisMonthLeads.reduce((sum, l) => {
    if (l.status === "Abandoned" || l.status === "Sale Closed") return sum;
    return sum + (SERVICE_CONVERSION_VALUES[l.service] ?? 1000);
  }, 0);

  const pipelineValue = leads.reduce((sum, l) => {
    if (l.status === "Abandoned" || l.status === "Sale Closed") return sum;
    return sum + (SERVICE_CONVERSION_VALUES[l.service] ?? 1000);
  }, 0);

  // ── Source segments for donut ──
  const directCount = leads.filter(l => !l.utm_source && !l.referrer).length;
  const googleCount = leads.filter(l => l.utm_source === "google" || l.utm_source?.includes("search")).length;
  const socialCount = leads.filter(l => l.referrer || (l.utm_source && l.utm_source !== "google")).length;

  const sourceSegments: DonutSegment[] = [
    { label: "Direct Traffic", count: directCount, color: "bg-white/40", hex: "rgba(255,255,255,0.5)" },
    { label: "Google / Search", count: googleCount, color: "bg-[#87A96B]", hex: "#60a5fa" },
    { label: "Referrer / Social", count: socialCount, color: "bg-purple-400", hex: "#c084fc" },
  ];

  const topSourceTip: Record<string, string> = {
    "Direct Traffic": "Most of your leads come directly — your brand awareness is strong. Consider adding referral incentives to grow this further.",
    "Google / Search": "Google leads are converting well. Consider increasing your budget for high-value treatment keywords like \"Dental Implants London\".",
    "Instagram": "Instagram is your top growth channel. Keep posting high-quality video content and case studies to maintain this traction.",
    "Referrer / Social": "Social/referral traffic is performing well. Ensure your profile links are up-to-date and your team is responding to comments.",
  };

  const forecastData = useMemo(() => {
    const P_NEW_TO_BOOKED = 0.30;
    const P_BOOKED_TO_TREATED = 0.70;

    // Calculate pipeline stages (fallback numbers if actuals aren't strictly available)
    const treatedValue = monthlySecuredRevenue || 15000;
    const bookedValue = pipelineValue || 20000;
    const newValue = (newLeads || 10) * 1500;

    const expectedRevenue = treatedValue + (bookedValue * P_BOOKED_TO_TREATED) + (newValue * P_NEW_TO_BOOKED * P_BOOKED_TO_TREATED);

    return [
      { date: 'Current', actual: treatedValue, predicted: treatedValue },
      { date: 'Month End Projection', actual: null, predicted: expectedRevenue }
    ];
  }, [monthlySecuredRevenue, pipelineValue, newLeads]);

  // Loss Aversion Metric (for header banner)
  const totalAtRisk = useMemo(() =>
    leads
      .filter(l => l.status === 'New Lead')
      .reduce((sum, l) => sum + (l.potential_value || SERVICE_CONVERSION_VALUES[l.service] || 1000), 0),
    [leads]
  );

  return (
    <div className="min-h-screen bg-[#0A0F1E] text-white font-sans">
      {session === null ? (
        <div className="flex items-center justify-center h-screen">
          <RefreshCw className="w-6 h-6 text-gray-400 animate-spin" strokeWidth={1.5} />
        </div>
      ) : (
        <>
          {/* ── CLINICAL LUXURY HERO HEADER ── */}
          <header className="sticky top-0 z-50 bg-[#08091A]/90 backdrop-blur-2xl border-b border-[0.5px] border-white/[0.07] shadow-[0_1px_0_rgba(255,255,255,0.04)]">
            <div className="max-w-7xl mx-auto px-6 py-3 flex items-center justify-between gap-6">

              {/* Left: Authority Metric Overlay */}
              <div className="flex items-center gap-3">
                <div className="h-6 w-[1.5px] bg-[#10B981]/40 rounded-full" />
                <div className="flex flex-col">
                  <span className="text-[9px] font-black uppercase tracking-[0.4em] text-[#A0A0A0]">Clinic Secured</span>
                  <span className="text-lg font-black tabular-nums text-[#2AF598] tracking-tighter drop-shadow-[0_0_10px_rgba(42,245,152,0.3)]">£{totalAtRisk.toLocaleString()}</span>
                </div>
              </div>

              {/* Centre: 3-Tab Nav (Ultimate Glass Capsule) */}
              <div className="flex bg-white/[0.03] backdrop-blur-3xl p-1.5 rounded-2xl border-[0.5px] border-white/10 shadow-2xl relative overflow-hidden group">
                <div className="absolute inset-0 bg-gradient-to-r from-emerald-500/5 to-cyan-500/5 opacity-0 group-hover:opacity-100 transition-opacity" />
                {(['action', 'pipeline', 'vault'] as const).map(tab => (
                  <button
                    key={tab}
                    onClick={() => setActiveTab(tab)}
                    className={`px-8 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-[0.25em] transition-all duration-500 relative z-10 ${
                      activeTab === tab
                        ? 'bg-[#10B981] text-[#0A0F1E] shadow-[0_0_25px_rgba(16,185,129,0.5)] scale-[1.02]'
                        : 'text-zinc-500 hover:text-white hover:bg-white/5'
                    }`}
                  >
                    {tab}
                  </button>
                ))}
              </div>

              {/* Right: Expert Mode + Profile (Tactile Interaction) */}
              <div className="flex items-center gap-4">
                {activeTab === 'vault' && (
                  <motion.div 
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-emerald-500/5 border border-emerald-500/10"
                  >
                    <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse shadow-[0_0_8px_rgba(16,185,129,0.5)]" />
                    <span className="text-[9px] font-black uppercase tracking-widest text-emerald-400">System Active | Last Scanned: Just now</span>
                  </motion.div>
                )}
                <button
                  onClick={() => setIsExpertModeOpen(true)}
                  className="p-2.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-2xl transition-all text-zinc-400 hover:text-emerald-400 hover:shadow-[inset_0_0_15px_rgba(16,185,129,0.2)]"
                  title="Control Center (Expert Mode)"
                >
                  <Settings className="w-5 h-5" />
                </button>
                <button
                  onClick={() => signOut()}
                  className="p-2.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-2xl transition-all text-zinc-500 hover:text-red-400"
                  title="Secure Exit"
                >
                  <LogOut className="w-5 h-5" />
                </button>
              </div>
            </div>
          </header>

          {/* ── MAIN CONTENT ── */}
          <main className={`transition-all duration-700 ease-in-out ${isExpertModeOpen ? 'blur-md scale-[0.98] opacity-60' : 'blur-0 scale-100 opacity-100'}`}>
            <AnimatePresence mode="wait">

              {/* ACTION TAB */}
              {activeTab === 'action' && (
                <motion.div
                  key="action"
                  initial={{ opacity: 0, y: 24 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -24 }}
                  transition={{ duration: 0.3 }}
                >
                  <ZeroDashboardView
                    leads={leads}
                    clinicId={profile?.clinic_id || ''}
                    specialty={profile?.specialty}
                    onStatusChange={updateStatus}
                    onImportComplete={fetchLeads}
                  />
                </motion.div>
              )}

              {/* PIPELINE TAB */}
              {activeTab === 'pipeline' && (
                <motion.div
                  key="pipeline"
                  initial={{ opacity: 0, y: 24 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -24 }}
                  transition={{ duration: 0.3 }}
                  className="max-w-7xl mx-auto px-6 py-10 space-y-8"
                >
                  <div className="flex justify-between items-end">
                    <h2 className="text-3xl font-black text-white tracking-tight">Lead Flow</h2>
                    <p className="text-xs font-bold text-gray-600 uppercase tracking-widest">{leads.length} total leads</p>
                  </div>

                  <div className="flex overflow-x-auto pb-10 gap-4 custom-scrollbar">
                    {KANBAN_COLUMNS.map(col => (
                      <KanbanColumn
                        key={col}
                        columnId={col}
                        columnLeads={leads.filter(l => l.status === col)}
                        setDepositModal={() => {}}
                        setSelectedLead={setSelectedLead}
                        updateStatus={updateStatus}
                        STAFF_LIST={dynamicStaffList}
                        updateAssignedTo={updateAssignedTo}
                        timeAgo={timeAgo}
                        clinic={profile}
                        onOpenPTMode={() => {}}
                        selectedDate={selectedDate}
                      />
                    ))}
                  </div>
                </motion.div>
              )}

              {/* VAULT TAB */}
              {activeTab === 'vault' && (
                <motion.div
                  key="vault"
                  initial={{ opacity: 0, y: 24 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -24 }}
                  transition={{ duration: 0.3 }}
                  className="max-w-2xl mx-auto px-6 py-20 space-y-10"
                >
                  <div className="text-center space-y-4">
                    <h2 className="text-3xl font-black text-white tracking-tighter uppercase italic">The Clinical Vault</h2>
                    <p className="text-zinc-400 font-bold uppercase tracking-[0.2em] text-[10px]">Authoritative Data Processing Engine ↗</p>
                  </div>

                  <div className="bg-[#1A1A2E] rounded-[44px] p-2 border border-white/10 shadow-2xl">
                    <CSVImportZone
                      clinicId={profile?.clinic_id || ''}
                      specialty={profile?.specialty}
                      onImportComplete={fetchLeads}
                    />
                  </div>
                </motion.div>
              )}

            </AnimatePresence>
          </main>

          {/* ── EXPERT MODE DRAWER ── */}
          <ExpertModeDrawer
            isOpen={isExpertModeOpen}
            onClose={() => setIsExpertModeOpen(false)}
          />

          {/* ── TOAST ── */}
          <AnimatePresence>
            {toast && (
              <Toast
                message={toast.message}
                type={toast.type}
                onClose={() => setToast(null)}
              />
            )}
          </AnimatePresence>
        </>
      )}
    </div>
  );
}

